### ISSUE TITLE
# bodhi Test scripts for testing

### ISSUE THREAD

**Issue by arjun1092** [project-sunbird/sunbird-commons#102]
we are unable to find the test scripts used to do the following tests 

o	Functional testing 
o	Performance testing
o	SOA testing
o	Mobile testing

Please provide the WSDL files to do SOA testing also.

If the test scripts are not yet open sourced, please mail it to the id: SHYAMPRASADKR@gmail.com

**Comment by kochhar** [comment]
1. Functional testing: @madhucr 
2. Perf testing: @mathewjpallan 
3. SOA testing: @madhucr 
4. Mobile testing: @mathewjpallan

**Comment by arjun1092** [comment]
hi  @madhucr @mathewjpallan , Can you please share the details at the earliest . 

@kochhar 

If the test scripts are not yet open sourced, please mail it to the id: SHYAMPRASADKR@gmail.com

**Comment by kochhar** [comment]
Hi @arjun1092, Sunbird test automation is WIP. If you'd like to contribute to this effort, you could start with API test automation. Please let me know and I will share the present API automation backlog with you.

Sunbird runs REST APIs not SOAP, so there isn't a WSDL available. Instead, you can find the REST documentation linked from the sunbird docs site: http://www.sunbird.org/apis/ From the API documentation pages, you can download the OpenAPI specification for each API group.

**Comment by arjun1092** [comment]
@kochhar : can you please shed some light on the tools used for the different tests.

**Comment by kochhar** [comment]
Presently, we're using Postman collections for writing API test cases. The
test case runs can be automated via Postman's console test runner: Newman.

If you would like to use any tools particular tools which are well suited
to REST API testing (and which can support OpenAPI spec or Swagger spec),
please do share your suggestions. We're at an early stage of implementation
and can consider alternatives.

Thanks!

**Comment by arjun1092** [comment]
@kochhar  why not soapui with swagger connector.?

**Comment by kochhar** [comment]
Please share some links to docs which explain how soapui can be scripted
via bash for test automation. I will share with the team and organise the
feedback on its suitability.

**Comment by arjun1092** [comment]
@kochhar : Do you want links which describes : how to execute Soapui , scripts  via CLI ?

**Comment by kochhar** [comment]
Hi @arjun1092, thanks a lot for the links. As of now, we don't understand the context around using SoapUI -- what are the problems with the alternatives and what kind of benefits would result from using SoapUI?

It would be useful for to create a one-page document which can help everyone involved understand the proposal you are making in detail. Here's an example of a document which was useful when deciding the authentication server to use in Sunbird.
https://docs.google.com/document/d/1fGWBvwRiIhjSV0O68w-tARU9AYIKEUlD5l0nQArUdsg/edit#heading=h.jn0enjryg2

Thanks a lot, look forward to reading the detailed proposal.

**Comment by arjun1092** [comment]
@kochhar  : I can go ahead with Postman.(I was yet to explore pm.* API when I posted this).

Please shed some light on tools used for functional @madhucr ,performance @mathewjpallan  and mobile testing @mathewjpallan )

**Comment by kochhar** [comment]
@arjun1092 sure, please go ahead with Postman. If you'd like to automate running the tests, Postman includes a console-based test runner called newman. This blog explains in more detail how to use newman to automate API tests from your build system. 
http://blog.getpostman.com/2015/09/03/how-to-write-powerful-automated-api-tests-with-postman-newman-and-jenkins/

As before, the API spec can be downloaded from the Sunbird API documentation hub: http://www.sunbird.org/apis/

**Comment by arjun1092** [comment]
@kochhar  I need information for the tools used for the rest as well for the Bodhi project .  Please let me know those details ate the earliest. 
What is the current status for SOA testing? Any specific pipeline or something is  already defined in jenkins ?
 Any specific syntaxes or conventions  to be followed while writing test scripts.?

**Comment by arjun1092** [comment]
hi @kochhar , Can you please provide the inputs for the query above. 

I need information for the tools used for the rest as well for the Bodhi project . Please let me know those details at the earliest.
What is the current status for SOA testing? Any specific pipeline or something is already defined in jenkins ?
Any specific syntax's or conventions to be followed while writing test scripts.?

**Comment by kochhar** [comment]
@arjun1092 the current tool used is postman. the API specification for postman can be downloaded from the sunbird.org/api_docs site. at present SOA testing is WIP. No pipelines have been defined.

When writing test-cases, please use Javascript test cases in Postman. 
Please ensure that environment details are abstracted into a postman environment so those details do not get introduced into the codebase.

For Javascript tests, please follow the [Standard JS](https://standardjs.com/) guidelines.
