### ISSUE TITLE
Need help with the version of Play framework and build tool used

### ISSUE THREAD

**Issue by Krish113** [project-sunbird/sunbird-commons#103]
Please specify the play framework version used. And if possible please provide info about the build tool and build script used

**Comment by kochhar** [comment]
@Krish113 you should be able to run the system using the scripts provided which pull the application services inside a docker container and deploy it.

**Comment by kochhar** [comment]
Hi @Krish113, I'm closing this issue, please re-open if you still need to install Play services.
