### ISSUE TITLE
API token error arising when installing sunbird

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/sunbird-commons#105]
From Naga Sai Abhishek Govula:

Hi,
                I’m following the documentation mentioned https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md
                In this document
                Step 4: Setup Application and Core services->inside this Obtain API token from Ekstep platform by following steps listed here(https://github.com/project-sunbird/sunbird-commons/wiki/Obtaining-API-token-for-accessing-ekstep-APIs).
                Here, I have done the steps required and for testing the JWT token, I am using Postman Rest client.
 
Regards,
Abhishek

cc: @coolbung

**Comment by coolbung** [comment]
Is he facing a problem ? How do we communicate with him and help resolve any issues ?

**Comment by Abhishek-Govula** [comment]
Hi,
  You can contact me on +91 9620204162, or email me on abhishek520.govula@gmail.com

**Comment by kochhar** [comment]
@coolbung seems there is an error when testing the EkStep API token with the EkStep APIs. I believe this token was generated from the EkStep community portal. Here's the relevant documentation for the API: https://community.ekstep.in/developer-apis/operation/ekstep.learning.content.read

@Abhishek-Govula can confirm.

**Comment by Abhishek-Govula** [comment]
Hi @kochhar 
The link mentioned is throwing a 404(Page not found).

For creating the JWT token, I have used the web-based tool mentioned in the documentation here ( [https://community.ekstep.in/developer-knowledgebase/45-getting-started-with-apis](https://community.ekstep.in/developer-knowledgebase/45-getting-started-with-apis) ). Tool is [http://jwtbuilder.jamiekurtz.com/](http://jwtbuilder.jamiekurtz.com/)

**Claims set used for generating the JWT**
```
{
  "iss": "8b6e3e8afe8943f6abd3ac0707275e61", // key generated while registering for the API credentials for EkStep developers
  "iat": 1510122682,
  "exp": 1510124420,
  "aud": "org.ekstep.api",
  "sub": "5a015037bef78" // user name generated after requesting for API access for EkStep developers
}
```
Signing used for the JSON Web Token : _secret generated while registering for the API credentials_

##
**Request Structure**
Url: https://qa.ekstep.in/api/content/v3/read/org.ekstep.num.scrn.basic
Headers: 
  Content-Type: application/json
  Authorization: Bearer _JWT created in the step above_
  Method: GET
 
##
**Response**
  Status Code: 403
  Body: 
```
  {
    "message": "No credentials found for given 'iss'"
  }
```

**Comment by kochhar** [comment]
@Abhishek-Govula Yes, the URL results in a 404 for some reason. Please follow the links for the Content Platform API docs from this page: https://community.ekstep.in/developer-apis

Could you share the generated JWT token? Secondly, if the services are also receiving the same access error when connecting to the EkStep APIs, please do share the service log files.

**Comment by Abhishek-Govula** [comment]
@kochhar, I have followed the same Platform API docs mentioned for generating the JWT token
JWT generated is eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI4YjZlM2U4YWZlODk0M2Y2YWJkM2FjMDcwNzI3NWU2MSIsImlhdCI6MTUxMDE1NzA1NSwiZXhwIjoxNTQxNjkzMDU5LCJhdWQiOiJvcmcuZWtzdGVwLmFwaSIsInN1YiI6IjVhMDE1MDM3YmVmNzgifQ.iitzrynEjNhVCjTutvx4zlG5OasIB-tsxMj3DiGFKws

I have not set up the services yet, this was needed to be added to the configuration file. So I''m trying to verify if the Auth is successful with this token, by using Postman API provided at _Run in Postman_ [https://community.ekstep.in/developer-knowledgebase/99-api-authentication](https://community.ekstep.in/developer-knowledgebase/99-api-authentication)

**Comment by kochhar** [comment]
@coolbung @Abhishek-Govula Resolved, the key was not matching with the URL. Closing out this issue.

**Comment by coolbung** [comment]
@Abhishek-Govula  while we update the docs, can you follow the same process to request access to groups on the EkStep QA environment - https://qa.ekstep.in/ I am standing by to approve the request so that you can generate the credentials for QA.

BTW, since this is a public issues board, please do not share credentials here.

**Comment by Abhishek-Govula** [comment]
Sure @coolbung , I have requested for the access to groups on the QA environment. Please approve :)

**Comment by coolbung** [comment]
Are you sure you asked for all groups ? Just see 2

**Comment by Abhishek-Govula** [comment]
@coolbung , I have requested for all the groups, now when I click on "Request for API access", I get the following "No groups to display or you have requested access for all the groups"

**Comment by coolbung** [comment]
Ok. Go ahead and create the credentials and then the JWT. Please use this for your test instance, and not the production one.

**Comment by Abhishek-Govula** [comment]
@kochhar , @coolbung  I am able to access the EkStep QA API with the new credentials now. Thank you for your help. :)

**Comment by coolbung** [comment]
Sounds good. Realised that your consumer will need access to a few more groups. Can you share the name of the consumer (you will see this in the username column) on https://qa.ekstep.in/api-credentials

Please mail the same to me so that we can update your consumer.

**Comment by Abhishek-Govula** [comment]
@coolbung apologies for the late reply, the consumer name is: ```5a03f1804ce01```

**Comment by ahghatol** [comment]
@Abhishek-Govula we have granted access to your consumer to few more groups. 

cc @coolbung

**Comment by kochhar** [comment]
closing this as permissions seem fixed.
