### ISSUE TITLE
Need standalone Player Code

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/sunbird-commons#109]
@sujeetkrjaiswal commented on [Thu Nov 09 2017](https://github.com/project-sunbird/sunbird-portal/issues/36)

Since there is no comments in the code, and there is no independent document for the portal app, If you can help with the finding the player code, which as discussed should be independent and self sufficient.

Since I am exploring, it would be much helpful, if we can have a demo page, which just demonstrates the player, with some hard-coded .ekar file input.

I also tried to explore the mobile source code, as it also uses the web-view of android to load the content, but the entire js file was a bundle, and I was not able to extract the player code.

From my exploration till now, My understanding of player is that there is some bare-bone structure of player code, which downloads the renderer as well along with any other plugin file required.

Since I am planning to modify some of the features of the player, like menu etc. It would be of much help, if I can have access to some of the documentation of flow of data and function in the player.

**Comment by kochhar** [comment]
@harishgilimi could you please help @sujeetkrjaiswal with references to the ekstep player code and the player plugin documentation.

**Comment by sujeetkrjaiswal** [comment]
@harishgilimi I tried creating a separate app, with player as a different module and added a dependency in main app, will just use a directive to play the content. The player part is not implemented, but I have added few basic thing. Will be adding to it as and when I understand things to it. It would be of much help, if you can take your time to help me finish this. The repo is at https://github.com/sujeetkrjaiswal/Bodhi

**Comment by Abhishek-Govula** [comment]
@sujeetkrjaiswal Update the README of the repo to show the installation and build instructions

**Comment by sujeetkrjaiswal** [comment]
@Abhishek-Govula Installation and build instruction for dev is done. For prod build and testing, things are not yet configured. But I hope, Dev setup should do for the given issue

**Comment by kochhar** [comment]
Also needed is the source for the authoring tool.
