### ISSUE TITLE
Error in the init-dbs.sh for cassandra

### ISSUE THREAD

**Issue by Abhishek-Govula** [project-sunbird/sunbird-commons#110]
Error in the file [https://github.com/project-sunbird/sunbird-devops/blob/master/ansible/roles/cassandra-cql-update/templates/cassandra.cql#L601](https://github.com/project-sunbird/sunbird-devops/blob/master/ansible/roles/cassandra-cql-update/templates/cassandra.cql#L601)

Here the script is trying to remove a non existing column named ``tcupdatedat`` from the table ```user``` in the keyspace ```sunbird```. This line is breaking the script and the subsequent cql commands are unable complete execution.

I have commented out this line and executed the script, noticing that the next line is adding a similar type of column. This ran successfully. Please let me know if this is alright or would it create any issues further.

**Comment by endeepak** [comment]
@vrayulu @manzarul @harishgilimi Can you please look into the Cassandra sql issue

**Comment by manzarul** [comment]
@endeepak  that delete script is not required , will delete it

**Comment by mathewjpallan** [comment]
@Abhishek-Govula Commenting the line is ok and you should not face any issues because of that. We have removed the drop column cql as it was not necessary.

**Comment by Abhishek-Govula** [comment]
@mathewjpallan Thank you for the confirmation. Using this script for now :)

**Comment by kochhar** [comment]
closing as this seems fixed
