### ISSUE TITLE
#bodhi No controller for sending and getting telemetry data.

### ISSUE THREAD

**Issue by ajinkya-k** [project-sunbird/sunbird-commons#112]
The telemetry events are directly sent to EkStep. Is there any controller for telemetry events in Sunbird? How to access the telemetry data from sunbird?

**Comment by kochhar** [comment]
@ajinkya-k sunbird provides dashboards for admins which provide summary views of the telemetry. for raw telemetry data you'll need to pull out the data from the ekstep platform.

**Comment by Abhishek-Govula** [comment]
@kochhar Is this data being sent to EkStep directly from the UI application or being routed through a sunbird hosted API?

**Comment by shyamprasadkr** [comment]
@kochhar Thanks for the response. We want to pull raw data using data exhaust apis. This requires license key. Ref:  https://community.ekstep.in/developer-apis/data-exhaust-api . @ajinkya-k  has raised the request for the same.   Can you please send it?

**Comment by coolbung** [comment]
@ajinkya-k Can you please submit a fresh request asking for only the 'Request and download datasets' group.

**Comment by coolbung** [comment]
Approved.

**Comment by ajinkya-k** [comment]
@coolbung The Data Exhaust API requires a License Key. Is this the same as the key?

**Comment by ajinkya-k** [comment]
@coolbung 
1. The Data Exhaust API requres a License Key. Is that the same as the API key?
2. The Data Exhaust API also requires a token in the SHA1 for the message field. Is that the same as the QA JWT token?

**Comment by coolbung** [comment]
Let me come back to you on the license key and how to get the SHA hash value.

Also, you should ask for the data exhaust API permission on qa.ekstep.in as well, since you're currently connecting sunbird to the QA platform. 

cc @navaneeth

**Comment by ajinkya-k** [comment]
@coolbung I have already requested access for QA data exhaust API

**Comment by coolbung** [comment]
Approved on QA

**Comment by navaneeth** [comment]
I'd recommend to use the On Demand Data exhaust API. Documentation is available at - https://community.ekstep.in/developer-apis/on-demand-data-exhaust-api#

**Comment by ajinkya-k** [comment]
@navaneeth 
What is the dataset_id used to identity which dataset to fetch?
Also, how do I obtain a client_key that required in the params

**Comment by navaneeth** [comment]
@ajinkya-k 


dataset_id | Type | Dataset
-- | -- | --
eks-consumption-raw | Consumption | Raw telemetry events
eks-consumption-summary | Consumption | Summary events
eks-consumption-metrics | Consumption | Metrics
eks-creation-raw | Creation | Raw telemetry events
eks-creation-summary | Creation | Summary events
eks-creation-metrics | Creation | Metrics
