### ISSUE TITLE
Issue while setting up the sunbird-devops after keycloak setup #bodhi

### ISSUE THREAD

**Issue by Abhishek-Govula** [project-sunbird/sunbird-commons#114]
I am trying to setup the [sunbird-devops](https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md), and was able to successfully setup the application until `/deploy-keycloak-vm.sh`.
The next step is to setup the realm [here](https://github.com/project-sunbird/sunbird-commons/wiki/Keycloak-realm-configuration). This documentation says that keycloak will be running as a docker service, but the existing installation has not run it in a docker container. Output of docker services running
```
# docker service ls
ID                  NAME                  MODE                REPLICAS            IMAGE                                   PORTS
gnc39e4c4qaq        adminutil_adminutil   replicated          1/1                 sunbird/adminutil:0.0.1-SNAPSHOT-gold   *:4000->4000/tcp
vi50w0snc8o4        api-manager_echo      replicated          1/1                 sunbird/echo-server:0.0.2-silver        *:9595->9595/tcp
z55ymej2b0j5        api-manager_kong      replicated          1/1                 sunbird/kong:0.9.9                      *:8000->8000/tcp,*:8001->8001/tcp
```

Keycloak is running fine and I am able to see the keycloak web page when I navigate to `http://<ipaddr>:8080/auth/`

Also the credentials added in the inventory configuration for `keycloak_admin_username` and `keycloak_admin_password` does not seem to be valid credentials when I go to Administration console of keycloak. I get the error saying invalid credentails

**Comment by kochhar** [comment]
@coolbung could you please take a look at this, seems that the documentation might still be referenced keycloak in docker.

**Comment by Abhishek-Govula** [comment]
I found where the installation is done and am able to login to the keycloak.
Download realm link [here](https://github.com/project-sunbird/sunbird-commons/wiki/Keycloak-realm-configuration#import-realm) does not seem to work. Can you please provide the realm download URL

**Comment by coolbung** [comment]
Here's the correct link -
https://raw.githubusercontent.com/project-sunbird/project-sunbird.github.io/dev/files/keycloak-realm.json

Thanks for pointing this out, we'll update the docs.

**Comment by coolbung** [comment]
Ref https://github.com/project-sunbird/project-sunbird.github.io/issues/65
