### ISSUE TITLE
Need help updating keycloak configs #bodhi

### ISSUE THREAD

**Issue by Abhishek-Govula** [project-sunbird/sunbird-commons#115]
I have setup keycloak server and setup the realm. Now the doc says to update the following configs

```
# Login to the keycloak admin console, goto the clients->admin-cli->Installation->Select json format
sunbird_sso_client_id: # Eg: admin-cli
sunbird_sso_username: # keycloak user name
sunbird_sso_password: # keycloak user password

# Login to the keycloak admin console, goto the clients->portal->Installation->Select json format
keycloak_realm:  # Eg: sunbird
sunbird_keycloak_client_id: # Eg: portal

# Login to the keycloak admin console, goto the clients->trampoline->Installation->Select json format
sunbird_trampoline_client_id:  # Eg: trampoline
sunbird_trampoline_secret:     # Eg: HJKDHJEHbdggh23737
```
goto the `clients->admin-cli->Installation->` **_I don't see a json format here_**, The available formats are

1. Keycloak OIDC JBoss Subsystem XML
2. Keycloak OIDC JSON

On selection of Keycloak OIDC JSON, I see the following JSON structure
```
{
  "realm": "sunbird",
  "auth-server-url": "http://localhost:8080/auth",
  "ssl-required": "external",
  "resource": "admin-cli",
  "public-client": true
}
```
Where do I update the configs as mentioned in the docs ? Please help

**Comment by kochhar** [comment]
@manzarul @harishgilimi could you please guide on this issue.

**Comment by Abhishek-Govula** [comment]
Can someone please help with the information. If needed, I can share my screen and show the exact error

**Comment by coolbung** [comment]
Please refer [this docs page](https://github.com/project-sunbird/sunbird-commons/wiki/Keycloak-realm-configuration
) to import the realm followed by a few steps to be performed in the Keycloak admin

Assuming you imported the sample realm, use the below values for config -

sunbird_sso_client_id: admin-cli
sunbird_sso_username: ## username for the user you created ##
sunbird_sso_password: ## password for the user you created ##

keycloak_realm:  sunbird
sunbird_keycloak_client_id: portal

sunbird_trampoline_client_id: trampoline
sunbird_trampoline_secret: ## secret that you regenerated for the trampoline client ##

**Comment by coolbung** [comment]
I just updated the docs page in the link above to add an important step about configuring user roles for the `user-manager` user.

**Comment by kochhar** [comment]
@Abhishek-Govula closing as this seems resolved. please re-open if the configuration problem persists.

**Comment by Abhishek-Govula** [comment]
The docs page mentioned in this [comment](https://github.com/project-sunbird/sunbird-commons/issues/115#issuecomment-345696484), says we need to save the secret and auth token and it will be used later. But except for `sunbird_trampoline_secret`, the others have not been used. Is this expected or am I missing any step in the configuration ?
