### ISSUE TITLE
Is there any documentation for mappings in Elasticsearch? #bodhi

### ISSUE THREAD

**Issue by pranvendra** [project-sunbird/sunbird-commons#116]
I want to know how the data is being stored in Elasticsearch. The indexes and its mapping. Right now, I am not able to find any documentaion for the same.

**Comment by kochhar** [comment]
@pranvendra At present these is not a document available for this. Welcome contributions from your side. Please let me know if you need guidance on how to go about contributing the documentation.

Thanks!
