### ISSUE TITLE
#bodhi Undefined telemetry event CP_IMPRESSION

### ISSUE THREAD

**Issue by ajinkya-k** [project-sunbird/sunbird-commons#117]
A telemetry event with id  `CP_IMPRESSION` is being generated from the Sunbird Staging portal. However, the API call to `https://staging.open-sunbird.org/private/service/v1/content/data/v1/telemetry
` is failing with the error `unable to find event definition for eid :cp_impression"`

**Comment by navaneeth** [comment]
Can you share the full event?
