### ISSUE TITLE
#bodhi Missing EID in Telemetry event JSON created on submitting feedback for content

### ISSUE THREAD

**Issue by ajinkya-k** [project-sunbird/sunbird-commons#118]
When user submits feedback after viewing content, the value for the key `eid` in the telemetry event JSON  is blank.

**Comment by vinukumar-vs** [comment]
Feedback of the content is not generating any event in portal. 
Content feedback functionality will work only in mobile(sending feedback telemetry to Genie-SDK)

@harishgilimi @vrayulu @AmiableAnil

**Comment by kochhar** [comment]
@harishgilimi what are the next steps for this issue?

**Comment by ajinkya-k** [comment]
@kochhar I have narrowed down the error the `sendFeedback` method in `TelemetryV2Manager`. It is making a call to `createEvent` with empty EID which is the first parameter

The `sendFeedback` method definition:
```
this.sendFeedback = function(eks) {
        return this.createEvent("", eks);
    };
```
The `createEvent` method signature
```
this.createEvent = function(eventName, body, consumer) 
```

**Comment by kochhar** [comment]
@vinukumar-vs @harishgilimi I believe the correct EID should be "OE_FEEDBACK". Could you please confirm?

**Comment by vinukumar-vs** [comment]
@kochhar
As I commented above, Genie-Canvas(ContentRenderer) is not logging any OE_FEEDBACK event(from end page rating). Content player is logging only GE_FEEDBACK when it is playing in mobile.

When the content is playing in portal(using ContentRenderer), there is no event generating feedback(OE_FEEDBACK) from the end-page as of now. 

 @mathewjpallan @harishgilimi @anujtech46 @AmiableAnil @sferoz

**Comment by kochhar** [comment]
@vinukumar-vs thanks for the confirmation that the eid should be OE_FEEDBACK. let's file a GenieCanvas bug.

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/sunbird-portal #227](https://github.com/project-sunbird/sunbird-portal/issues/227) via [**ZenHub**](https://www.zenhub.com/)
