### ISSUE TITLE
#Bodhi creating content in sunbird 

### ISSUE THREAD

**Issue by Kavya1403** [project-sunbird/sunbird-commons#119]
While creating study material what does the different resource types signify when ultimately all the options take us to the editor and the study material is available as resource after saving the content.

**Comment by kochhar** [comment]
@nadayogi can explain this in better detail. perhaps this needs a faq from the @project-sunbird/techwriters

**Comment by Sunitashelar** [comment]
Adding  glossary to Sunbird documentation website
