### ISSUE TITLE
Need information regarding application and database #Bodhi

### ISSUE THREAD

**Issue by Abhishek-Govula** [project-sunbird/sunbird-commons#123]
I need the following information 

**Database**
1. Are there any data initialization scripts?
2. Are the any initial entries for ORG, ROLE, USERS etc,.
3. Which application is using MongoDB? And for what purpose is it being used ?
4. Is there any seed data which gets initiated on launch of any application? If so, can you please point to it?

**Application**
1. How do I test if the apis are working ? (To see the list of apis, I am using https://hostname/apis?size=200)
2. What is the Authorization header that should be used to access these API ?
3. How do I register my own application with keycloak for development (I want to create new APIs as extension of the existing sunbird api. Can I register to keycloak and allow communication between them securely?)
4. What are the creds for super user? (The user who creates the organizations and grants the existing uses permissions. Is this the same ```user-manager``` created while creating the realm on keycloak?)

**Comment by kochhar** [comment]
documentation! documentation!! documentation!!!
jokes aside, yes these docs are needed. @Abhishek-Govula perhaps a meeting in person may be more efficient at getting you started with the sunbird application.

**Comment by Abhishek-Govula** [comment]
@kochhar. Yes indeed. I’m nearly ready setting up the application. Some developer level documentation would be great. If possible, we can meetup this week some day. We are available on weekends as well ;)
