### ISSUE TITLE
"Access Denied" after login to the portal. #Bodhi

### ISSUE THREAD

**Issue by Abhishek-Govula** [project-sunbird/sunbird-commons#124]
I successfully setup the application and trying to login to the portal.

Creds used: `user-manager` user created [here](https://github.com/project-sunbird/sunbird-commons/wiki/Keycloak-realm-configuration)

After the successful login, the page is redirected to `https://hostname/private/index?auth_callback=1&state=a18b1c02-6289-479d-8e6d-b43b2ba77ffd&code=uss.LqIiSd-qIIpwtp0rIzj-l4VFoldIYkjGERKvCRh1Dbo.85e94245-0604-4d8c-8f4b-ade81f14c3c0.8c12290d-d62f-48ce-913b-c93bf995ca59`

**Request** 
```
Request method: GET
Remote address: hostipaddres
Status code: 403
```

**Request headers**
```
Host: 172.20.10.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Cookie: connect.sid=s%3AM5s3HgMY7AwYw8AUfnOxSSrs33hzGYgz.4kWqVzr7hM%2B4ulqCMPrbjOnfgKh55zRVvOj1esQ8yNI
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```

**Response**
```
Access denied
```

**Response header**
```
Server: nginx/1.13.3
Date: Tue, 21 Nov 2017 15:12:16 GMT
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: Express
```

Can you point in a direction where the error might be?

**Comment by Abhishek-Govula** [comment]
@kochhar Any help on this please ?

**Comment by kochhar** [comment]
@Abhishek-Govula seems the application is not being able to validate your login. is the player application configured with the correct auth server address? could you verify the [config entries](http://www.sunbird.org/developer-docs/installation/installing_sunbirdon_laptop/#link1-1-3) for the player?

**Comment by kochhar** [comment]
@harishgilimi any tips on debugging the 403?

**Comment by harishgilimi** [comment]
@kochhar it happens when keycloak config is not correct, @Abhishek-Govula please check your keycloak config using admin console

**Comment by Abhishek-Govula** [comment]
@harishgilimi I have setup the keycloak as per the docs once again.

I am using self signed certificates and the following are the logs
```
# docker service logs player_player --tail 200
player_player.1.7uk5k43q2dwh@kmadmin    | app running on port 3000
player_player.1.w9278szhiinv@kmadmin    | app running on port 3000
player_player.1.w9278szhiinv@kmadmin    | Could not obtain grant code: Error: unable to verify the first certificate
player_player.1.cu8xdxmlvhkd@kmadmin    | app running on port 3000
player_player.1.cu8xdxmlvhkd@kmadmin    | Could not obtain grant code: Error: unable to verify the first certificate
player_player.1.cu8xdxmlvhkd@kmadmin    | Could not obtain grant code: Error: unable to verify the first certificate
player_player.1.cu8xdxmlvhkd@kmadmin    | Could not obtain grant code: Error: unable to verify the first certificate
player_player.1.aja1vloeu0bu@kmadmin    | app running on port 3000
player_player.1.9jas5ysae9qx@kmadmin    | app running on port 3000

```

**Comment by Abhishek-Govula** [comment]
@harishgilimi

I have created the realm and clients using the json file provided in the document [here](https://github.com/project-sunbird/sunbird-commons/wiki/Keycloak-realm-configuration). Also the document here says the secret and registration access token will  be used later, but except for the `sunbird_trampoline_secret`, other secrets or the access tokens are not used anywhere. Is this expected ?

**Comment by kochhar** [comment]
Hi Abhishek, could you please try with verifiable certificate? The error
logs show that the certificate cannot be verified.

On 24-Nov-2017 11:17 am, "Abhishek Govula" <notifications@github.com> wrote:

@harishgilimi <https://github.com/harishgilimi>

I have created the realm and clients using the json file provided in the
document here
<https://github.com/project-sunbird/sunbird-commons/wiki/Keycloak-realm-configuration>.
Also the document here says the secret and registration access token will
be used later, but except for the sunbird_trampoline_secret, other secrets
or the access tokens are not used anywhere. Is this expected ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/project-sunbird/sunbird-commons/issues/124#issuecomment-346747803>,
or mute the thread

**Comment by Abhishek-Govula** [comment]
@kochhar I don't have a valid certificate right now, so I have disabled the check on the nodejs environment using `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"`

I deleted the old realm and created a new realm again by following the documentation mentioned [here](https://github.com/project-sunbird/sunbird-commons/wiki/Keycloak-realm-configuration).

The certificate error is gone, but I am getting the following error

```
Validate grant failed
player_player.1.z7kkdekmi540@kmadmin    | Grant validation failed. Reason: invalid token (wrong ISS)
player_player.1.z7kkdekmi540@kmadmin    | TypeError: Cannot read property 'access_token' of undefined
player_player.1.z7kkdekmi540@kmadmin    |     at Object.getCurrentUserRoles (/home/sunbird/dist/helpers/permissionsHelper.js:84:36)
player_player.1.z7kkdekmi540@kmadmin    |     at getUserData (/home/sunbird/dist/server.js:238:25)
player_player.1.z7kkdekmi540@kmadmin    |     at /home/sunbird/dist/node_modules/async/dist/async.js:3853:24
player_player.1.z7kkdekmi540@kmadmin    |     at replenish (/home/sunbird/dist/node_modules/async/dist/async.js:946:17)
player_player.1.z7kkdekmi540@kmadmin    |     at /home/sunbird/dist/node_modules/async/dist/async.js:950:9
player_player.1.z7kkdekmi540@kmadmin    |     at eachOfLimit (/home/sunbird/dist/node_modules/async/dist/async.js:975:24)
player_player.1.z7kkdekmi540@kmadmin    |     at /home/sunbird/dist/node_modules/async/dist/async.js:980:16
player_player.1.z7kkdekmi540@kmadmin    |     at _parallel (/home/sunbird/dist/node_modules/async/dist/async.js:3852:5)
player_player.1.z7kkdekmi540@kmadmin    |     at Object.series (/home/sunbird/dist/node_modules/async/dist/async.js:4708:5)
player_player.1.z7kkdekmi540@kmadmin    |     at Keycloak.keycloak.authenticated (/home/sunbird/dist/server.js:236:9)
player_player.1.z7kkdekmi540@kmadmin    |     at keycloak.getGrantFromCode.then.err (/home/sunbird/dist/node_modules/keycloak-connect/middleware/post-auth.js:45:20)
player_player.1.z7kkdekmi540@kmadmin    |     at runMicrotasksCallback (internal/process/next_tick.js:64:5)
player_player.1.z7kkdekmi540@kmadmin    |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
player_player.1.z7kkdekmi540@kmadmin    |     at process._tickCallback (internal/process/next_tick.js:104:9)
player_player.1.z7kkdekmi540@kmadmin    | Could not obtain grant code: Error: Can't set headers after they are sent.
```

Please let me know if there is a way to debug this.

Also, it would be great if you can let me know if self signed certificate is being used in the development environment and if so, how are you by-passing the certification check.

**Comment by kochhar** [comment]
No we are not using a self-signed certificate. We have a wildcard cert which applies to dev domain also.

**Comment by harishgilimi** [comment]
@Abhishek-Govula can you check the mongodb config in portal, is it running and connected ?

**Comment by Abhishek-Govula** [comment]
@harishgilimi Mongodb is running and also storing session data

**Comment by harishgilimi** [comment]
@Abhishek-Govula can we have hangout call to figure it out, i see the keycloak node module is not storing authtoken in session.
cc: @coolbung @kochhar

**Comment by Abhishek-Govula** [comment]
@harishgilimi Yes, please. Please let me know the time. Anytime is fine with me.

**Comment by harishgilimi** [comment]
@Abhishek-Govula because of deployment i little busy today will do it on Monday at 10:30AM, is this time fine for you ?

**Comment by Abhishek-Govula** [comment]
Yes. I am available. Please share your email id. I will send you hangout request

**Comment by harishgilimi** [comment]
Thanks you @Abhishek-Govula  add me<harishg@ilimi.in> and Aswin<coolbung@gmail.com> in the request.

**Comment by harishgilimi** [comment]
@Abhishek-Govula  from hangout call i can see in browser url after auth there are two slashes 
Eg: https://www.sunbird.com/auth//somthingElse

So the extra slash will give that issue please update **sunbird_portal_auth_server_url** without slash at the end
cc @kochhar @coolbung @vrayulu

**Comment by Abhishek-Govula** [comment]
@harishgilimi . It's working now. Thanks for the help.

Please update the configuration file created by the automation script [`generate-config.sh` ](https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md#preparation). It is adding the extra slash in the end. Sample [file](https://github.com/project-sunbird/sunbird-devops/blob/master/ansible/inventories/sample/group_vars/sample#L76)

**Comment by kochhar** [comment]
@Abhishek-Govula We'd welcome a pull-request with the fix.
