### ISSUE TITLE
Information needed regarding the "retire" endpoint for content #Bodhi

### ISSUE THREAD

**Issue by Abhishek-Govula** [project-sunbird/sunbird-commons#125]
The content retire API endpoint `https://staging.open-sunbird.org/api/content/v1/retire` being used to delete the content or list of content.

On the EkStep environment, is this API soft deleting the content being created on the S3 storage or is it being permanently deleting the content which cannot be undone ?

I wanted to know if it is possible to access the list of resources deleted by the user.

**Comment by kochhar** [comment]
The EkStep APIs are documented at https://community.ekstep.in/developer-apis/ 
Please see the content service APIs for more details.

https://community.ekstep.in/developer-apis/content-platform-api
Sorry, I can't link to the exact API, for some reason those links result in 404s.
