### ISSUE TITLE
Issue when fetching a plugin in the player

### ISSUE THREAD

**Issue by sujeetkrjaiswal** [project-sunbird/sunbird-commons#127]
When the player is trying to access

http://localhost:3000/content/preview/coreplugins/org.ekstep.toaster-1.0/renderer/libs/toaster.min.js??411&_=1512221710779

when /content/preview/* is proxied for 'https://staging.open-sunbird.org'
Getting the following errors:
```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>5F5613E608784F57</RequestId>
  <HostId>
    G0efMZCbVW2QdT4at7xX8N/WADhQjU7gMDhmZs9yibt7py7lN3rUIitx9e8mpdSHehkD3qLQ1TU=
  </HostId>
</Error>
```

Can someone help with the reason for this error and how to fix this?

**Comment by kochhar** [comment]
@harishgilimi please take a look

**Comment by kochhar** [comment]
@vinukumar-vs please seems like there is an error in loading plugins.

**Comment by vinukumar-vs** [comment]
There is an issue in ContentRenderer while bundling the plugins. We will address this issue in this Dec release.

@kochhar @harishgilimi

**Comment by kochhar** [comment]
@vinukumar-vs is there an interim workaround?

**Comment by kochhar** [comment]
@vinukumar-vs could you please share a bug link here?

**Comment by vinukumar-vs** [comment]
@kochhar 
https://github.com/ekstep/Genie-Canvas/issues/1563

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/sunbird-portal #226](https://github.com/project-sunbird/sunbird-portal/issues/226) via [**ZenHub**](https://www.zenhub.com/)
