### ISSUE TITLE
#bodhi timeStamp issue in OE_START and OE_END

### ISSUE THREAD

**Issue by ajinkya-k** [project-sunbird/sunbird-commons#132]
In the sunbird-portal telemetry, when `OE_START` is created and a corresponding `OE_END` is pushed to the `TelemetryV2Manager._end` queue, the time that is stored as `ets` in `OE_START` is different from the time that is stored in the queue OE_END event that is used to calculate the `edata.eks.length` when the `OE_END` event is actually fired. As a result, the actual time spent on the content is miscalculated. Ideally, `OE_START` `ets` must match with the startTime used for calculating OE_END `edata.eks.length`

**Comment by kochhar** [comment]
Thanks for the bug report @ajinkya-k. Could you please submit a PR for the fix? Thanks!

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/sunbird-portal #161](https://github.com/project-sunbird/sunbird-portal/issues/161) via [**ZenHub**](https://www.zenhub.com/)
