### ISSUE TITLE
#Bodhi

### ISSUE THREAD

**Issue by Kavya1403** [project-sunbird/sunbird-commons#136]
Sunbird Staging API's are throwing unauthorized error.

**Comment by kochhar** [comment]
Unfortunately, sunbird staging APIs do not have any uptime guarantee. This is documented in the setup instructions. If this is a blocking issue, we suggest following the remaining [instructions to deploy your own API services](http://www.sunbird.org/developer-docs/installation/deploy_sb_services/)
