### ISSUE TITLE
Sunbird Installation - DB Initialization - Loading CSV files

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-commons#137]
> Once DB initialisation is done then load following to CSV files

The above instruction from installation docs (http://www.sunbird.org/developer-docs/installation/setup_db/) is not very clear on where to load these CSV files. Is it possible to provide details about how to load these files also? 

Thank you. 

@Manojvv @kochhar @mathewjpallan @rjshrjndrn

**Comment by santhosh-optit** [comment]
We have to update the documentation (http://www.sunbird.org/developer-docs/installation/setup_db/). Its done automatically through ansible scripts. You don't need to load them manually

**Comment by bachia** [comment]
Great. Thank you.
