### ISSUE TITLE
Sunbird Installation - KeyCloak server installation

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-commons#138]
Documentation doesn't clearly specify on which server (db server / app server) KeyCloak software should be installed. 

http://www.sunbird.org/developer-docs/installation/keycloak_realm_configuration/

Where should this software be installed?

@kochhar @Manojvv @mathewjpallan @rjshrjndrn

**Comment by Manojvv** [comment]
It can be installed on any server(db server/app server). Preferred is app server. 

Will update the docs, thanks.

**Comment by bachia** [comment]
Thank you @Manojvv 

I believe we have to install Java also right? Any particular version that I should be installing so that the same version is compatible with Sunbird services also?

**Comment by Manojvv** [comment]
Openjdk-8  is installed via script. You dont need to install manually for keycloak. For the sunbird services java is installed inside the docker.

**Comment by bachia** [comment]
Thanks again @Manojvv 

But as per documentation, the app server was not prepped at all. I am trying to install keycloak on app server. So I guess I need to install openjdk-8 manually because no script was run so far. Please confirm.

**Comment by Manojvv** [comment]
Under this file : http://www.sunbird.org/developer-docs/installation/deploy_sb_services/
 Under the `Keycloak provisioning` RUN ./provision-keycloak.sh <implementation-name>-devops/ansible/inventories/<environment-name> 

will install the java. Document is still having some issues.  @rjshrjndrn Please check the document of keycloak.

**Comment by bachia** [comment]
Thank you @Manojvv 

Basically, I have to deploy_sb_services after initializing dbs I suppose. I was just following the installation instructions line by line. I understand that it is still work in progress.

**Comment by nawabahmadreshi** [comment]
@bachia , 
FYI
the sidebar is a logical sequence of installation process 
Medium Scale Deployment
Provisioning Servers
Setup Databases
      Preparation to Setup Databases
      Create Databases using automation
      Create Databases Manually
      Initialize Databases
Configure Keycloak
Deploying Sunbird Services
Customizing Assets
Check Installation

Will definitely tweak the content to ensure the rich installation experience.

Thanks
:CC
@Sunitashelar

**Comment by bachia** [comment]
@nawabahmadreshi Thank you. 

But I believe "Configure Keycloak" should come after "Deploying Sunbird Services". You may make a note of it and change the documentation as appropriate. 

@Manojvv got the following error while deploying keyclock `deploy-keycloak-vm.sh`

> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'keycloak_theme_path' is undefined\n\nThe error appears to have been in '/home/sluser/sunbird-devops/ansible/roles/keycloak/tasks/deploy.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: copy the artifacts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'keycloak_theme_path' is undefined"}

@Sunitashelar @mathewjpallan @kochhar

**Comment by rjshrjndrn** [comment]
@bachia 
deploy-keycloak-vm.sh should work now. Changed the theme field from mandatory to optional.
please pull the master and try once.

Regards,
Rajesh

**Comment by nawabahmadreshi** [comment]
@rjshrjndrm

Request you to kindly update the corresponding documentation page on sunbird doc website

**Comment by bachia** [comment]
@rjshrjndrn 

Looks like one more variable is having an issue. Details below : 

> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'keycloak_theme_path' is undefined\n\nThe error appears to have been in '/home/sluser/sunbird-devops/ansible/roles/keycloak/tasks/deploy.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: copy the artifacts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'keycloak_theme_path' is undefined"}
...ignoring

TASK [keycloak : XML file] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'keycloak_postgres_host' is undefined"}

**Comment by Manojvv** [comment]
Hi @bachia , Can you please check the `keycloak_postgres_host` variable in `<implementation-name>-devops/ansible/inventories/<environment-name> ` set or not. Also please share the screenshot of error if possible.

**Comment by bachia** [comment]
@Manojvv 

Yes, the variable is set to private IP address of DB server

Here is the full screenshot
![screen shot 2018-01-12 at 6 00 09 am](https://user-images.githubusercontent.com/2817641/34854214-4d8deff0-f75e-11e7-8044-f47bbcf9460c.png)
 of the output of the script.

**Comment by Manojvv** [comment]
@bachia Thanks for  sharing the screenshots ,Above error is bit strange, as the variable is passed on group_vars still the error is coming.  I just cross verified in my test environment script  worked fine. 
 
For debugging purpose , can you please share output of below commands .

1) Full command ran for `deploy-keycloak-vm.sh`
2)`git status` inside sunbird-devops folder.
2) `git branch` inside sunbird-devops folder.
3) `git pull --rebase` inside sunbird-devops folder.

Thanks,
Manoj V V

**Comment by rjshrjndrn** [comment]
@bachia 
Hi, copying artifacts will fail because you haven't specified any custom theme path for keycloak.
But still that step is not necessory. please have a look at this [commit](https://github.com/project-sunbird/sunbird-devops/commit/6de2df77ce777d91688da8c452055452f1c073b1#diff-2eef66ad88de9b6ec285f04d8e2cd7fd), as from now on keycloak will skip copying themes, if no custom themes are specified.

**Comment by rjshrjndrn** [comment]
@bachia  Please pull the latest master branch.

Regards, 
Rajesh.

**Comment by bachia** [comment]
@Manojvv 

Here are the details you had asked for 

deploy-keycloak-vm.sh command 
`sudo ./deploy-keycloak-vm.sh sl-dev-devops/ansible/inventories/`

`git status` output 

![screen shot 2018-01-12 at 9 50 45 am](https://user-images.githubusercontent.com/2817641/34859783-a1bebb2a-f77e-11e7-86df-83dad1c569f9.png)

`git branch` output

![screen shot 2018-01-12 at 9 51 00 am](https://user-images.githubusercontent.com/2817641/34859794-b86b13d2-f77e-11e7-84fd-02eac7fc95f8.png)

`git pull --rebase` output

![screen shot 2018-01-12 at 9 51 25 am](https://user-images.githubusercontent.com/2817641/34859799-c6a4a53a-f77e-11e7-87a5-3c414710572d.png)

**Comment by Manojvv** [comment]
@bachia 
in the command which you shared above  ,, please check arguement path once, missing `<environment-name>` at end.

for example "sudo ./deploy-keycloak-vm.sh sl-dev-devops/ansible/inventories/dev"

**Comment by bachia** [comment]
@Manojvv 

I just followed what is there in the install instructions. 

http://www.sunbird.org/developer-docs/installation/deploy_sb_services/

Looks like what you had suggested is missing. Let me try with the env and get back to you.

**Comment by bachia** [comment]
@Manojvv back to following error 

`sudo ./deploy-keycloak-vm.sh sl-dev-devops/ansible/inventories/development/`

> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'keycloak_theme_path' is undefined\n\nThe error appears to have been in '/home/sluser/sunbird-devops/ansible/roles/keycloak/tasks/deploy.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: copy the artifacts\n ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'keycloak_theme_path' is undefined"}

**Comment by Manojvv** [comment]
@rjshrjndrn Please note all the points above, and update the document. 

@bachia  Please pull again latest and try.

**Comment by bachia** [comment]
@Manojvv no luck same error

**Comment by Manojvv** [comment]
@bachia Sorry for inconvenience, Please pull again and try again.

**Comment by bachia** [comment]
@Manojvv it worked this time. Moving on to next step.

**Comment by bachia** [comment]
@rjshrjndrn @Manojvv 

keycloak auth url works now. But I am unable to get to login page because, keycloak is expecting HTTPS whereas I am accessing using HTTP

Any ideas?

**Comment by bachia** [comment]
@rjshrjndrn @Manojvv 

I did a fix in the keycloak DB to allow HTTP connections to admin. Now I am able to login and moving on to next step of configuring the sunbird realm. But this should be addressed as part of keycloak deployment.

**Comment by rjshrjndrn** [comment]
@bachia 
You have to deploy proxy because keycloak won't allow HTTP connections as you mentioned above.
After deploying proxy, https://proxy-dns-name/auth will take you to the admin console.

Regards,
Rajesh

**Comment by bachia** [comment]
@rjshrjndrn you are suggesting that I run `deply-proxy.sh` script before configuring keycloak realm?

**Comment by rjshrjndrn** [comment]
@bachia 
Yes, please.

**Comment by bachia** [comment]
@rjshrjndrn confirmed working. I updated the value in keycloak database back to default i.e., SSL required and ran `deploy-proxy.sh` script. I am able to access keycloak admin interface without using HTTP and also on port 80. Thanks for your help. 

Please make sure documentation is updated so that people like me don't run into these issues. 

Closing this issue.

@nawabahmadreshi @Sunitashelar @Manojvv @kochhar @mathewjpallan
