### ISSUE TITLE
SunBird Laptop Manual Installation- Editing environmentVariablesHelper.js and connecting to SunBird Portal

### ISSUE THREAD

**Issue by SMYALTAMASH** [project-sunbird/sunbird-commons#139]
i'm trying to launch a SunBird App by following the documentations in the "http://www.sunbird.org/developer-docs/installation/installing_sunbirdon_laptop/" but i'm unable to connect to sunbird Portal, can you provide some details as to what needs to be configured in environmentVariablesHelper.js file and how do i connect to SunBird Portal with it by providing Some Sample Data, Below is the Document which shows that it is not connected to SunBird
![help](https://user-images.githubusercontent.com/30286162/34819669-6232d760-f6e4-11e7-8ab9-f2e72d28fa29.png)

**Comment by rjshrjndrn** [comment]
@harishgilimi can you please check this?

**Comment by harishgilimi** [comment]
@SMYALTAMASH  please run you are app on port 3000 , let me know if you still face issue

**Comment by SMYALTAMASH** [comment]
I ran the app on port serverIP:3000 itself.

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/sunbird-portal #221](https://github.com/project-sunbird/sunbird-portal/issues/221) via [**ZenHub**](https://www.zenhub.com/)
