### ISSUE TITLE
Link not reachable

### ISSUE THREAD

**Issue by dhayalram123** [project-sunbird/sunbird-commons#14]
In documentation mentioned 2 links for docs and demo for the platform

1) [https://demo.open-sunbird.org/](https://demo.open-sunbird.org/)
2) [https://docs.open-sunbird.org/](https://docs.open-sunbird.org/)

Both the links are not reachable. Can you help us here!

**Comment by parthlawate** [comment]
Where should this be going @kochhar @vrayulu ?

**Comment by vrayulu** [comment]
@parthlawate - the demo of the platform should be going to https://staging.open-sunbird.org..

@kochhar - is there a separate docs site available?

**Comment by kochhar** [comment]
docs to the documentation link: http://open-sunbird.org/docs/

**Comment by parthlawate** [comment]
I think the docs team should be able to update that directly but we will need a deployment when they change that. @Sunitashelar should be able to do that. @lakhanmandloi pls assist

Also note that we do have the direct domain mapped now http://sunbird.org So @vrayulu you should be able to map the demo links etc from there too
