### ISSUE TITLE
Sunbird Installation - error while deploying apis

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-commons#140]
Encountered following errors while running `deploy-apis.sh` script

> PLAY [swarm-manager] ********************************************************************************************************************
skipping: no hosts matched

PLAY [swarm-manager] ********************************************************************************************************************
skipping: no hosts matched

@Manojvv @kochhar @mathewjpallan

**Comment by Manojvv** [comment]
@bachia Can you please share the `deploy-api.sh ` script command which you ran.

**Comment by bachia** [comment]
My bad @Manojvv 

Now that you had asked, I realize the path give was different. Apologies. 

Closing the issue.
