### ISSUE TITLE
Sunbird customization - Unable to use custom logo etc

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-commons#141]
Followed instructions provided here 

http://www.sunbird.org/developer-docs/installation/cust_sunbird/

Made appropriate changes i.e., set the `player_tenant_dir `

`player_tenant_dir: /home/sluser/data/extensions/tenant`

Changed the folder permissions as suggested. 

![screen shot 2018-01-12 at 12 40 15 pm](https://user-images.githubusercontent.com/2817641/34863497-c90460ce-f795-11e7-8dce-ba827e7ef545.png)

Ran `deploy-core.sh` and `deploy-proxy.sh` scripts even though it was not mentioned in the documentation. Expected changes were not reflected in the portal. 

https://dev.shikshalokam.org

@kochhar @mathewjpallan @Manojvv @rjshrjndrn @nawabahmadreshi

**Comment by Manojvv** [comment]
@bachia 
Just small clarification, Are you using source code for  sunbird-portal or deploying using docker image? 

If you are using source code, You need to copy the tenant folder manually. And set the `sunbird_default_tenant`(default vaule is sunbird) environment variable to your tenant folder name. Restart the player service.

If you are using the docker service deployment, 
In the `{implementation-name}-devops/ansible/inventories/{environment-name}/group_vars/{environment-name>}` update the `sunbird_default_tenant` variable and `player_tenant_dir`. Try by re-running `deploy-core.sh` script.

**Comment by bachia** [comment]
@Manojvv 

thank you. It works now. Had to set the value of `player_tenant_dir` also. That did the trick. Looks like this instruction needs to go to documentation as well. 

Closing this issue.

@nawabahmadreshi
