### ISSUE TITLE
Database Backup Mechanism #Bodhi

### ISSUE THREAD

**Issue by pranvendra** [project-sunbird/sunbird-commons#142]
Hi, 
I wanted to know how the backup of databases is taken on sunbird and what is the restoring process for the same. Moreover, if the backup is happening on regular basis.

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/sunbird-devops #26](https://github.com/project-sunbird/sunbird-devops/issues/26) via [**ZenHub**](https://www.zenhub.com/)
