### ISSUE TITLE
Sunbird website - generic comments

### ISSUE THREAD

**Issue by Sunitashelar** [project-sunbird/sunbird-commons#2]
1) The font colour on the internal pages should be 5% darker?
2) Increase the font size on the tiles of the documentation landing page. 
3) The font type on the Contact page is different from the rest of the site. It should be made consistent.
4) the ''Contact" tab on the header should be modified to 'Contact Us'. 
5) the links from the footer do not work
6) pages provided have not been linked.

**Comment by lakhanmandloi** [comment]
1) Color made bit more darker
2) Font size increased 
3) WIP
4) Contact renamed to contact us
5) Functional Now
6) WIP

**Comment by kochhar** [comment]
@Sunitashelar can you please verify the fixes and close this issue?

**Comment by kochhar** [comment]
Closing this issue. @Sunitashelar please create a fresh issue if items are pending.
