### ISSUE TITLE
Sunbird.org : certain parts of the website are not working

### ISSUE THREAD

**Issue by surendrasinghs** [project-sunbird/sunbird-commons#22]
- [x] Certain parts of the website are not working with new domain.

sunbird.org/architecture
sunbird.org/apis
sunbird.org/developer-docs

sunbird.org/features-documentation - seems to be working (static content)

- [ ] The favicon is also outdated / not as expected

**Comment by kochhar** [comment]
Hi @parthlawate, @lakhanmandloi: the documentation site is having some problems when accessed from sunbird.org instead of open-sunbird.org. Could you please take a look?

**Comment by lakhanmandloi** [comment]
Hi @surendrasinghs @kochhar @parthlawate 
Seems to be some server related issue. Even i was unable to open any page of site for some time. Now it seems to up and working. Can you please cross check ?

**Comment by lakhanmandloi** [comment]
Hi @surendrasinghs @kochhar 
Can we use the same favicon as of this site ? - https://staging.open-sunbird.org

**Comment by surendrasinghs** [comment]
@lakhanmandloi @kochhar Yes, it seems intermittently working.

Favicon : No, it cannot be same as staging open-sunbird. Please take it from Prasad in design team.

**Comment by kochhar** [comment]
@lakhanmandloi yes, the server was non-responsive. I have hupped it and it's back up. devops will be adding some monitoring as well

**Comment by parthlawate** [comment]
All working fine for me now @lakhanmandloi pls coordinate with prasad for any assets you need. You have met him today :)

**Comment by lakhanmandloi** [comment]
@PrasadSandbhor Hi Prasad. Can we get favicon for this site?
