### ISSUE TITLE
Add "UP Board" as board for NTP sunbird

### ISSUE THREAD

**Issue by mohitga** [project-sunbird/sunbird-commons#24]
Please add "UP Board" as a value in the board field in NTP.
Source Alia.

**Comment by mohitga** [comment]
@vrayulu please take in this weeks deployment

**Comment by aliaali** [comment]
Thanks, We have dependency for around 300 content coming on to NTP prod in time for Sept 5.

**Comment by Abhign** [comment]
@mohitga This issue is resolved hence i am closing this issue..
