### ISSUE TITLE
Footer Text  in  https://staging.ntp.net.in

### ISSUE THREAD

**Issue by vinod303** [project-sunbird/sunbird-commons#25]
Observed the following in the   https://staging.ntp.net.in  while testing.
 While creating a lesson, the footer says the following

"By proceeding you agreed to make all lesson created through authoring
tool or uploaded on the Ek Step platform to be available under licence
CC-BY 4.0 "

1) I think we have stopped calling "Authoring Tool"
2)Also, pls. see Ek Step(a space in between)

**Comment by juthikaqa** [comment]
@vinod303 PMs need to check this issue

**Comment by Abhign** [comment]
@vinod303 There is no space between EkStep..
