### ISSUE TITLE
NTP - browser compatibility

### ISSUE THREAD

**Issue by vinod303** [project-sunbird/sunbird-commons#26]
If the platform works better in Chrome, i think we should display that somewhere as it shown here http://mhrd.gov.in/.
The browser crashed couple of times while testing(https://staging.ntp.net.in)  couple of days back

**Comment by lakhanmandloi** [comment]
@vinod303 Can you please confirm on which browser you faced the issue? @kochhar @parthlawate

**Comment by vinod303** [comment]
@lakhanmandloi  - firefox 52.0 - this was about a week back
