### ISSUE TITLE
Login Page title shows - Login to Sunbird

### ISSUE THREAD

**Issue by vinod303** [project-sunbird/sunbird-commons#27]
in the Login page - (
https://staging.ntp.net.in/auth/realms/sunbird/protocol/openid-connect/auth?client_id=portal&state=d1208a96-f76e-4843-805d-9cedf5d5f9d9&redirect_uri=https%3A%2F%2Fstaging.ntp.net.in%2Fprivate%2Findex%3Fauth_callback%3D1&scope=openid&response_type=code#!/content/edit/do_2123206859170365441741
)

the page title (ie. the title meta tag ) says - "Login to Sunbird "
Shouldn;t be  "Login to NTP " ?

**Comment by juthikaqa** [comment]
Now it's "Login to DIKSHA"

**Comment by Abhign** [comment]
@vinod303 This issue is fixed hence i am closing this issue.
