### ISSUE TITLE
Listing all the Licenses in open sunbird

### ISSUE THREAD

**Issue by deepshikha2k5** [project-sunbird/sunbird-commons#29]
Please lists all the third party licenses. @kochhar @vrayulu

**Comment by kochhar** [comment]
Keycloak - Apache License 2.0
MongoDB Drivers - Apache License 2.0
PostgreSQL Drivers - ??
Cassandra Drivers - ??

**Comment by harishgilimi** [comment]
## Node Modules:

    "async": "^2.5.0",
    "body-parser": "^1.17.2",
    "connect-mongo": "^1.3.2",
    "dateformat": "^2.0.0",
    "eslint": "^3.19.0",
    "express": "^4.15.3",
    "express-http-proxy": "^1.0.6",
    "fine-uploader": "^5.14.5",
    "gulp-ng-config": "^1.4.0",
    "js-md5": "^0.5.0",
    "jsonwebtoken": "^7.4.1",
    "keycloak-connect": "3.2.0",
    "lodash": "^4.17.4",
    "request": "^2.81.0",
    "ua-parser-js": "^0.7.13",
    "uuid": "^3.1.0"
    "better-console": "^1.0.0",
    "connect-history-api-fallback": "^1.3.0",
    "ejs": "^2.5.6",
    "eslint": "^4.3.0",
    "eslint-config-airbnb-base": "^11.3.1",
    "eslint-plugin-import": "^2.7.0",
    "express-session": "^1.15.3",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "2.3.1",
    "gulp-cache": "^0.2.10",
    "gulp-chmod": "^2.0.0",
    "gulp-chug": "^0.5.1",
    "gulp-clean": "^0.3.2",
    "gulp-clean-css": "^3.4.1",
    "gulp-clone": "^1.0.0",
    "gulp-concat": "^2.6.1",
    "gulp-concat-css": "^2.3.0",
    "gulp-connect": "^2.2.0",
    "gulp-dedupe": "0.0.2",
    "gulp-filter": "^2.0.2",
    "gulp-gzip": "^1.4.0",
    "gulp-header": "^1.8.8",
    "gulp-imagemin": "^2.4.0",
    "gulp-inject": "^4.2.0",
    "gulp-jshint": "^1.11.1",
    "gulp-json-editor": "^2.2.1",
    "gulp-karma": "0.0.5",
    "gulp-less": "^3.3.0",
    "gulp-load-plugins": "^0.10.0",
    "gulp-minifier": "^0.2.2",
    "gulp-minify-css": "^1.2.0",
    "gulp-minify-html": "^1.0.6",
    "gulp-ng-annotate": "^1.0.0",
    "gulp-plumber": "^1.0.1",
    "gulp-print": "^2.0.1",
    "gulp-replace": "^0.5.4",
    "gulp-rev": "^5.0.1",
    "gulp-rev-replace": "^0.4.2",
    "gulp-test": "0.0.6",
    "gulp-uglify": "^1.2.0",
    "gulp-useref": "^3.0.0",
    "gulp-util": "^3.0.6",
    "gulp-watch": "^4.2.4",
    "jasmine-core": "^2.6.1",
    "jshint-stylish": "^1.0.0",
    "karma": "0.12",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "lazypipe": "^0.2.4",
    "map-stream": "0.0.7",
    "merge-stream": "^1.0.1",
    "open": "0.0.5",
    "path": "^0.12.7",
    "phantomjs-prebuilt": "^2.1.14",
    "require-dot-file": "^0.4.0",
    "rimraf": "^2.4.0",
    "run-sequence": "^1.1.1",
    "wiredep": "^2.2.2"

##  Bower Components:

    "angular": "1.6.0",
    "angular-cookies": "1.6.0",
    "angular-route": "1.6.0",
    "jquery": "^3.2.1",
    "angular-ui-router": "^1.0.3",
    "moment": "^2.18.1",
    "angular-pagedown": "^0.4.4",
    "slick-carousel": "^1.6.0",
    "angular-translate": "^2.15.1",
    "angular-sanitize": "1.6.0",
    "jquery-ui": "^1.12.1",
    "jquery.fancytree": "fancytree#^2.23.0",
    "file-upload": "./node_modules/fine-uploader/",
    "angular-uuid4": "^0.3.1",
    "izimodal": "~1.5.0",
    "js-md5": "md5#^0.5.0",
    "izitoast": "^1.1.4",
    "chart.js": "^2.6.0",
    "angular-chart.js": "^1.1.1"
    "angular-mocks": "1.6.0",
    "ngstorage": "^0.3.11",
    "jasmine-jquery": "^2.1.1",
    "lodash": "^4.17.4",
    "semantic-ui-calendar": "^0.0.8"

**Comment by manzarul** [comment]
**Cassandra** -

groupId -com.datastax.cassandra
artifactId -cassandra-driver-core
version -3.1.0

groupId -com.datastax.cassandra
artifactId -cassandra-driver-mapping
version -3.1.0

groupId -com.fasterxml.jackson.core
artifactId -jackson-databind
version -2.9.0.pr3

**Comment by manzarul** [comment]
**ElasticSearch**-

groupId -org.elasticsearch.client
artifactId -transport
version -5.4.3

**Comment by manzarul** [comment]
**Akka Actor**

groupId -com.typesafe.akka
artifactId -akka-actor_2.11
version -2.5.1

groupId -com.typesafe.akka
artifactId -akka-slf4j_2.11
version -2.5.1

groupId -com.typesafe.akka
artifactId -akka-remote_2.11
version -2.5.1

groupId -com.typesafe.akka
artifactId -akka-testkit_2.11
version -2.5.3

**Comment by manzarul** [comment]
**Quartz Job**
groupId -org.quartz-scheduler
artifactId -quartz
version -2.2.1

groupId -org.quartz-scheduler
artifactId -quartz-jobs
version -2.2.1

**Comment by manzarul** [comment]
**Postgresql**
groupId -org.postgresql
artifactId -postgresql
version -42.1.4

**Comment by manzarul** [comment]
**keyCloack**
groupId -org.keycloak
artifactId -keycloak-admin-client
version -3.2.0.Final

groupId -org.jboss.resteasy
artifactId -jaxrs-api
version -3.0.11.Final
groupId -org.jboss.resteasy
artifactId -resteasy-client
version -3.1.0.Final

**Comment by manzarul** [comment]
**Azure**
groupId -com.microsoft.azure
artifactId -azure-storage
version -5.4.0

**Comment by manzarul** [comment]
**Email Service**
groupId -org.apache.velocity
artifactId -velocity-tools
version -2.0

groupId -javax.mail
artifactId -javax.mail-api
version -1.5.1

groupId -com.sun.mail
artifactId -javax.mail
version -1.6.0

**Comment by manzarul** [comment]
**Play framework**

groupId -com.googlecode.json-simple
artifactId -json-simple
version -1.1

groupId -com.typesafe.play
artifactId -play_2.11
version -2.4.6

groupId -com.typesafe.play
artifactId -play-netty-server_2.11
version -2.4.6

groupId -com.typesafe.play
artifactId -play-specs2_2.11
version -2.4.6

groupId -org.scala-lang
artifactId -scala-library
version -2.11.8

**Comment by manzarul** [comment]
**Others**

groupId -junit
artifactId -junit
version -RELEASE

groupId -com.google.code.gson
artifactId -gson
version -2.2.2

groupId -com.fasterxml.jackson.core
artifactId -jackson-core
version -2.8.9

groupId -com.fasterxml.jackson.core
artifactId -jackson-databind
version -2.8.9

groupId -com.opencsv
artifactId -opencsv
version -3.8

groupId -org.powermock
artifactId -powermock-api-mockito
version -1.6.4

groupId -org.powermock
artifactId -powermock-module-junit4
version -1.6.4

groupId -org.apache.httpcomponents
artifactId -httpclient
version -4.5.1

groupId -com.typesafe
artifactId -config
version -1.3.0

**Comment by sferoz** [comment]
team - Please create a file third-party-licenses.md in the repo and add this there. Also, please include top level important dependencies and their license like Shailesh has done. The primary intent is to find the nature of licenses.

**Comment by kochhar** [comment]
Also, we need to filter out the runtime dependencies -- build and test deps (like junit, gulp) should be separated out.
