### ISSUE TITLE
Resource bundle for login screen

### ISSUE THREAD

**Issue by deepshikha2k5** [project-sunbird/sunbird-commons#30]
Please share the multilingual string for login screen. @kochhar

**Comment by kochhar** [comment]
Here is the resource bundle. These will need to be localised. Please select only the relevant strings from lines 1-97

https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/messages/messages_en.properties

**Comment by kochhar** [comment]
Also please add

locale_te=<Telegu in telegu script>
locale_ta-IN=<tamil in tamil script>
locale_hi_IN=<hindi in devanagari script>

**Comment by deepshikha2k5** [comment]
Received resource bundle. Closing Issue
