### ISSUE TITLE
Deployment Architecture 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/sunbird-commons#31]
@steotia 
Please find two files for installation procedures.
1 . Small scale deployment process 
2. Large Scale deployment process. 

You can start your content adding here :
sunbird-commons/Hackathon/smallmedium_deploy_process.md
sunbird-commons/Hackathon/largescale_deploy_process.md

**Comment by lakhanmandloi** [comment]
@kochhar @nawabahmadreshi @Sunitashelar content from these files, Are they intended to go on Sunbird documentation site http://open-sunbird.org/ ? 

cc @parthlawate

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi 
Yes, there is change in these files, I will be updating the files by tomorrow EoD,

**Comment by kochhar** [comment]
these files will move from the Hackathon directory and into the main documentation structure. @nawabahmadreshi and @lakhanmandloi can determine the best location.

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi where do we want to show this page? and when this page is expected to show? I mean is it urgent or okay if goes after 2-3 weeks with new designs.

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi
Yes this is important and highly prioritised section. I will complete it by tomorrow and, I will also let you know where this section needs to be put in. I hope this will answers your question.

**Comment by kochhar** [comment]
@nawabahmadreshi is this done? can the issue be closed?

**Comment by nawabahmadreshi** [comment]
This is done , closing the issue .
