### ISSUE TITLE
Sunbird - home page links are not working

### ISSUE THREAD

**Issue by vinod303** [project-sunbird/sunbird-commons#33]
in http://open-sunbird.org/  -  the  links in the  home pages (NOT THE TOP MENU)  are not working.

**Comment by kochhar** [comment]
hi @lakhanmandloi can you please check and fix

**Comment by lakhanmandloi** [comment]
@vinod303 @kochhar Hi, I am unable to replicate this issue. Can you please share exact links and there position on page?

**Comment by vinod303** [comment]
@lakhanmandloi  http://open-sunbird.org/
On the home page , there are links along with description as below; in this case "About Sunbird". Those links are not working

![image](https://user-images.githubusercontent.com/15699608/30004448-fd7acaa6-90ec-11e7-9f89-ca7b765fdeee.png)
@kochhar

**Comment by lakhanmandloi** [comment]
@vinod303 Was able to replicate. Sometimes it works while sometimes it doesn't. Although it is a simple html a tag. Will try to debug the same in details and update you. @kochhar @parthlawate

**Comment by parthlawate** [comment]
Working for me..

**Comment by vinod303** [comment]
@lakhanmandloi  the issue is with Firefox. It is working for me in Chrome when tested.
