### ISSUE TITLE
Link from docs site to github project is needed

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/sunbird-commons#35]
@lakhanmandloi 

The sunbird.org home page needs to be updated to have a link to the github repositories. 

1. Update the section with the github+source-code image to read "Full documentation available on github" to read "Fully open-source, check out the source on github" with a link to the project-sunbird github. (https://github.com/project-sunbird)
1. Add another link to the top navigation-bar titled "source-code" which links to the github project

cc: @nadayogi, @sunitashelar

**Comment by Sunitashelar** [comment]
@kochhar,@lakhanmandloi,@nadayogi
we are working towards revamping the sunbird.org site. the site information architecture, design and navigation are undergoing a change. we will take up these changes in the revamped design. Looking to implement the changes within 2 weeks.

**Comment by lakhanmandloi** [comment]
@Sunitashelar Noted. Thanks! :) 

cc: @parthlawate

**Comment by parthlawate** [comment]
@Sunitashelar Is the Info Arch for the Documentation section changing as well or only the main site and landing pages ? 

As some refactoring we want to do to simplify the Jeckyl piece which is dependent on the Documentation Info Arch

**Comment by kochhar** [comment]
@Sunitashelar Please do incorporate navigation to the sunbird source as an element when redesigning the site navigation. 

However, changing one line of text and adding a link is:
a. urgently needed as a bug-fix
a. relatively minor
a. independent of the site design and information architecture revamp

Please do not make this dependent on the site revamp.

@lakhanmandloi

**Comment by lakhanmandloi** [comment]
@kochhar will send updated code in some time.

**Comment by lakhanmandloi** [comment]
@Sunitashelar  @nawabahmadreshi The compiled output of latest documentation seems to be broken. and can be seen on http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/architecture/. We need to fix it.  

@kochhar Providing you the old site version which is currently deployed on live with following changes -
1. changes asked by you 
2. Removing search - as currently it is not functional
you can check this on - http://sunbird.cloudaccess.host/

Sending you the zip in email.

**Comment by lakhanmandloi** [comment]
@kochhar link to download for this version - https://drive.google.com/open?id=0B27vogzDj2QROVZBTDdwNFBZRGs

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi we will check the linking and fix it asap

**Comment by kochhar** [comment]
closing as link is added.
