### ISSUE TITLE
About Plugins 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/sunbird-commons#36]
https://community.ekstep.in/developer-knowledgebase/111-how-do-i-think-about-a-plugin
Is this all we have about plugins? @kochhar 

I don't feel this provides comprehensive information about plugins .Please provide point of contact for the same if you can .

**Comment by kochhar** [comment]
The link to the documentation on creating a plugin is on the same page.

**Comment by nawabahmadreshi** [comment]
fine will check it , thank you .
