### ISSUE TITLE
Adding members to repo's on sunbird

### ISSUE THREAD

**Issue by harshithaks** [project-sunbird/sunbird-commons#38]
Please add Design@EkStep team to the following repo's:

sunbird documentation
Sunbird app 
Sunbird community interactions
Sunbird consumption of courses on web, profiles. 

Let me know when this is done.

@kochhar

**Comment by kochhar** [comment]
Hi @harshithaks. Design@EkStep team does not exist as yet in sunbird. Could you please create the team and add the people to it? I have sent you an invitation to join the project with admin rights

**Comment by harshithaks** [comment]
@kochhar Will do. Thank you!

**Comment by harshithaks** [comment]
@kochhar I don't have "invite member" access on this organisation. Unable to add members to the team.

**Comment by kochhar** [comment]
@harshithaks closing this issue since the access has been resolved
