### ISSUE TITLE
Error message list for UI relevance

### ISSUE THREAD

**Issue by deepshikha2k5** [project-sunbird/sunbird-commons#39]
Please provide us with the list of all error messages, relevant for the UI. Below is the link for all the error messages lists:

https://docs.google.com/spreadsheets/d/1qrXFCiqQ9SOyUXVg13HWfRJzv35VJQCWZhmkK1Qf7Es/edit#gid=0

 @harishgilimi , @vrayulu

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/sunbird-portal #5](https://github.com/project-sunbird/sunbird-portal/issues/5) via [**ZenHub**](https://www.zenhub.com/)
