### ISSUE TITLE
Unable to add mentors or members to a batch for a course

### ISSUE THREAD

**Issue by bangaloreprasad** [project-sunbird/sunbird-commons#41]
Team,

I logged in as a course mentor, searched for a course and added a batch. However, am not able to add either mentors or members to the batch. 

Thanks,
Prasad
![issue_unable to add mentors or members to a batch](https://user-images.githubusercontent.com/25506743/30205995-4e51f4c2-94a8-11e7-85d0-c1df1f294fb1.png)

**Comment by juthikaqa** [comment]
Invalid- Works fine on Diksha
- I have already discussed and demonstrated on Diskha . it works fine.
On Staging we have issue and It's known to QA. Even I sent an email to issue reporter stating that once it's fixed on Staging I will inform him so that he can on staging

**Comment by bangaloreprasad** [comment]
Staging is also equally important as we have activities, which restrict us from using the live (Diksha) environment.

This issue is open for over a week on staging. Hope it is resolved sooner.

**Comment by mohitga** [comment]
@vrayulu please look into this issue?
I should be working on QA as well if it is working on Production,
