### ISSUE TITLE
Burger menu obstructing the content in the background

### ISSUE THREAD

**Issue by bangaloreprasad** [project-sunbird/sunbird-commons#45]
Team,

The burger menu is obstructing the content in the background. 

Suggestion: the menu be made to appear on swipe from left corner. A tab like protrusion can be made to appear on the side.

Thanks,
Prasad[
![issue_hamburger_menu_obstructing_details](https://user-images.githubusercontent.com/25506743/30289206-0a5ad90c-9749-11e7-81d7-fe6d7d6f5369.png)
](url)

**Comment by Abhign** [comment]
@bangaloreprasad This is the known issue UI team is looking in to it.
