### ISSUE TITLE
Issue while saving content metadata

### ISSUE THREAD

**Issue by Jayaprakash8887** [project-sunbird/sunbird-commons#46]
Dear Team,

Couple of issues noticed while saving content metadata.

Steps:
1. Upload a Content and click 'Edit details'
2. Fill only few of all mandatory fields and click 'Save'

Issues:
1. Message stating which other mandatory fields are missing data
2. Fields filled doesnt get committed into the system. (Close content and re-open content to check metadata)

Warm regards,
JP

**Comment by Abhign** [comment]
User expects errors should be displayed on the pop up.
This is an improvement.
