### ISSUE TITLE
Critical!! Confusion between 'Content Type' and 'Resourse Type'

### ISSUE THREAD

**Issue by Jayaprakash8887** [project-sunbird/sunbird-commons#48]
Dear Team,

While uploading a content, metadata displays 'Resourse Type' as a mandatory field. But in filters in 'Library' menu has 'Content Type' as a search parameter. Values of both lists are different. When I fech details of a content through API, I can see both parameters for a content: 'contentType' and 'resourseType'. Need to sort this in application.

Warm regards,
JP

**Comment by Abhign** [comment]
This is an improvement.
Will be enhanced
