### ISSUE TITLE
dropdown value navigation issue.

### ISSUE THREAD

**Issue by Jayaprakash8887** [project-sunbird/sunbird-commons#50]
Dear Team,

Go to 'Edit Details' of a content.
click on 'Subject'
click 'M' to navigate through the list with values stating with 'M' (Ex: Malayalam, Marathi, Mathematics...)

Navigation is not happening through all values.

Warm regards,
JP

**Comment by Abhign** [comment]
QA team has verified.Will be added to the issue list.

**Comment by kochhar** [comment]
@Abhign is this added to the backlog?
