### ISSUE TITLE
'All' option required in 'Board' dropdown for content

### ISSUE THREAD

**Issue by Jayaprakash8887** [project-sunbird/sunbird-commons#51]
Dear Team,

Please add 'All' option as an option to 'Board' dropdown.

Warm regards,
JP

**Comment by Abhign** [comment]
@Jayaprakash8887 ,This is an enhacement.
Product Manager need to check.

**Comment by kochhar** [comment]
@Abhign Please assign this issue or close it.

**Comment by Abhign** [comment]
@kochhar This issue is resolved hence i am closing this issue ..
