### ISSUE TITLE
Filter search issue in 'Library'

### ISSUE THREAD

**Issue by Jayaprakash8887** [project-sunbird/sunbird-commons#53]
Dear Team,

Go to 'Library' menu --> click on 'Filters' --> Click on 'Medium' 

1. One can select multiple mediums. Is this correct functionality?
2. If #1 is Yes, then search is not working when multiple values are selected.

Warm regards,
JP

**Comment by Abhign** [comment]
@Jayaprakash8887 
1. One can select multiple mediums. Is this correct functionality?
Ans:- True that is feature how it is developed.
2. If #1 is Yes, then search is not working when multiple values are selected. 
Ans:- search is working fine, it is not replaceable.

**Comment by Jayaprakash8887** [comment]
Issue has got fixed
