### ISSUE TITLE
Critical! User creation API failing

### ISSUE THREAD

**Issue by Jayaprakash8887** [project-sunbird/sunbird-commons#54]
Environment: NTP Production.

Tried to create a user through postman(details below). On first request, got service error, On subsequent requests getting 'username/email already exists' error. Not able to find the user/email in the user list query. However, able to login using the emailid.

"firstName": "Bindu",
"lastName": "Thirumalai",
"provider":"tiss",
"email": "bindu.thirumalai@tiss.edu",
"userName":"BinduThirumalai",
"emailVerified": true

**Comment by vrayulu** [comment]
@Jayaprakash8887 - i think this issue is resolved now. Please close if CreateUser is working now.
