### ISSUE TITLE
Community APIs on website 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/sunbird-commons#58]
@lakhanmandloi 
We dont have "communities" in this release of Sunbird. Kindly delete the same. 
Also,  kindly note that API documentation is in progress. Since, APIs have changed and same will be provided to you after being reviewed by @Sunitashelar @kochhar
Link for your reference
http://sunbird.org/apis/core
cc @Sunitashelar

**Comment by kochhar** [comment]
suggest we delete the source swagger files till we are ready to make them
live. the community APIs (under core APIs) are still evolving.

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi @kochhar So Just to confirm -
I have to remove "Sunbird API"  Section from page - http://sunbird.org/apis/ so that nobody can access http://sunbird.org/apis/core/. or the entire API Documentation from - http://sunbird.org/docs/?

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi 
Please keep sunbird API section as it is. You can link it to something which says " Sunbird APIs will be available soon".

**Comment by kochhar** [comment]
Please only remove the link to the core APIs section. Please leave the
others in-place till we can review them.

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi  , I have edited the html files for APIs , I have just made a slight change i.e 

I have set  file-path as comment.



Can you please rebuild the website .

**Comment by lakhanmandloi** [comment]
@kochhar @nawabahmadreshi Can you pls confirm this is okay? - http://sunbird.cloudaccess.host/apis/

**Comment by lakhanmandloi** [comment]
@kochhar link to zip - https://drive.google.com/open?id=0B27vogzDj2QRajdXTkJrczRBQm8
This zip also includes Google Analytics integration

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi, This is not right, I had removed the links to API swagger files in corresponding html pages and accordingly I had requested you to rebuild the website again. 

What we intend to do is  that API hrefs  as on content  model API ,Composite search  API, Domain model API should not direct to any page as such till we get latest swagger files reviewed and approved.

**Comment by nawabahmadreshi** [comment]
Done and updated accordingly .
