### ISSUE TITLE
Sunbird API documentation contacts are incorrect

### ISSUE THREAD

**Issue by sferoz** [project-sunbird/sunbird-commons#59]
The API documentation has website, contact email and IRC chat channel that are incorrect. Please verify and correct it. Below is the current sample.

http://sunbird.org/apis/core/#

> Contact: apis@sunbird.io License: Unknown Find out more about Swagger
> 
> This is a Sunbird server. You can find out more about Sunbird at http://sunbird.edu or on irc.freenode.net, #sunbird. For this example, you can use the api key special-key to test the authorization parts of the API.

**Comment by nawabahmadreshi** [comment]
@sferoz 
I have added all necessary information to the API headers. This API isn't meant to go live as of now, since communities part is under process, we have directed @lakhanmandloi to de-llink till APIs are throughly reviewed and the process will take  2-3 days.
