### ISSUE TITLE
[Installation] Basic sunbird installation

### ISSUE THREAD

**Issue by steotia** [project-sunbird/sunbird-commons#60]
Need
- automation
- documentation 

to get
- basic Sunbird installation
- customize the appearance.

**Comment by steotia** [comment]
@vrayulu Need documentation on how a Sunbird installation can hit the Ekstep Infra APIs (API consumer/channel onboarding). 
@kochhar Need documentation on auth. setup.

**Comment by nawabahmadreshi** [comment]
@steotia Basic Sunbird Installation (Developer Installation) is available . 
here 
https://github.com/project-sunbird/sunbirdcommons/blob/master/Hackathon/developer_installation.md

Regarding customizing appearance documentation , it is awaited. 
@kochhar when can we expect this to be available .

**Comment by steotia** [comment]
@nawabahmadreshi This issue is towards having a intermediate pre Production setup on a server. The README will be updated to cover this scenario.

**Comment by nawabahmadreshi** [comment]
@steotia , fine . I thought this might help .

**Comment by steotia** [comment]
Configuration will contain the URLs for media (logo, stylesheets, etc) overrides. The URLs could be CDN (recommended) URLs or picked from the filesystem. All Dockerfiles should have a configurable mount point (preferably /extensions) to pick media assets from the filesystem (/extensions/media) or binaries (/extensions/software).
The mount point to pick up media assets is not optimal since assets need to be manually copied over to each server but is the lowest starting point for smaller or developer installations.
@vrayulu Can you pick the Dockerfile modifications and change application code to pick the overrides? Maybe you can assign this to @Manojvv

**Comment by steotia** [comment]
Need one configuration file (key:value pairs) for each service - <service-name>.env.sample (YAML format) to be in a `/configurations` folder in each service repo. This sample file should contain possible configurations for service boot up with comments briefly describing the key.
Thoughts? @vrayulu

**Comment by steotia** [comment]
These are the following steps for installation:

Lets assume there are 2 VMs:
(1) for all services
(2) for all DBs

Pre-reqs to figure out: 
(1) OS
(2) capacity, e.g. 2 servers with 4 core, 4 GB RAM each, etc

1. Install various DBs (with links to respective DB installation scripts)
2. Clone the DevOps repository
3. Run DB init scripts cc @vrayulu (do we have these scripts?)
4. Edit configuration files (@Manojvv has provided a bunch of samples)
5. Run `install.sh` to install Docker Swarm mode
6. Run `setup.sh` to install service dependencies (e.g. do we need Keycloak? @vrayulu )
7. Run `deploy.sh` to install Sunbird core services (-c config files folder as modified earlier)
8. Run `smoke.sh` to check if installation is working fine (optional)

**Comment by steotia** [comment]
Installation steps at https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md

**Comment by steotia** [comment]
Next steps:
- configuring keycloak
- customizing appearance

**Comment by kochhar** [comment]
Tracking appearance customisation here: https://github.com/project-sunbird/sunbird-commons/issues/69

**Comment by kochhar** [comment]
Keycloak configuration instructions are available on the [installation instruction site](http://www.sunbird.org/developer-docs/installation/medium_scale_deploy/) about 3/4 of the way down the page.
