### ISSUE TITLE
Content ready to go-live on Sunbird website

### ISSUE THREAD

**Issue by deepshikha2k5** [project-sunbird/sunbird-commons#65]
Hello Lakhan

Please can you rebuild the site. Please make a new tile on the website for "Frequently Asked Question"
@lakhanmandloi 

cc-
@Sunitashelar 
@nawabahmadreshi 
@Basreena 

Thanks & Regards

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi  , I have deleted the hackathon folder , Now re-building the website should not be a problem.

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi Hi, Thank you :)

@deepshikha2k5 Hi, regenerating site will be not possible as we have done sidebar related changes. If we regenerate the site,  we will loose those changes. The problem will get automatically fixed  in new upcoming designs. 

Till new design comes in i will have to manually add the content in site. So can you pls mentions files that has changes. so that i can put it there on right place. 

cc:
@parthlawate

**Comment by kochhar** [comment]
@lakhanmandloi this should have been done in a different branch so that the
master branch is always build-able. Please treat the docs repo as code. It
is not encouraged to have the master branch be in a non-buildable state.

What is the timeline for the first automated build-and-deploy?

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi  We have some content which needs to go live ASAP .

**Comment by deepshikha2k5** [comment]
@lakhanmandloi, nawabahmadreshi 
Please be informed that all the tree structure for Product Feature will remain the same except few changes. The content inside every landing page need to be updated, same as updated in <sunbird-commons>pages>feature documentation>

Per se few changes to be made in the tree structure are as follows:
1. Content Lifecycle - Here next sub-section that will come under it are: "content editor  > publishing > upload"
2. Guidelines - Intellectual Property and rest will be same as before

Please check and ensure that the images that displays are of correct size and aligned properly. Rest of the changes in the content need to be updated. Please let me know for the needful in this regard.

**Comment by lakhanmandloi** [comment]
@kochhar Hi, We are ready with CircleCI Integration for build and deploy to s3 as well as Github repos. Sending you calender request to discuss about the same. 

@deepshikha2k5 @nawabahmadreshi - Pls review the latest site at - http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi, didn't get you!

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi, site is not rendering properly, checked the markdown of developer doc. Installation .Also images giving some inline errors

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi I mean to say, i have removed the barrier of manual updating. Now we can built the site from command. You can edit the content in md files. For sidebar navigation you will have to links in /includes/sidebar.html file.

**Comment by nawabahmadreshi** [comment]
Great , So it means what we edit in .md files , we can see the changes instantly after executing the command

**Comment by nawabahmadreshi** [comment]
We need to set this website alright (talking about content).We had linked appropriate snippets  to corresponding master pages but I can see that the linking might just not be right . I will check it myself and set it right then we can rebuild it again . 
**Thank you for your support and cooperation , its appreciated.**

**Comment by deepshikha2k5** [comment]
@lakhanmandloi 
Hello Lakhan,
I saw the link that you have send. 
- Please can you replace the tile name "NTP FAQ's" to "Frequently Asked Question". 
- Few of the content in the site link is old, can you please update them with the latest file version. 
- Please check the images in NTP FAQ's doc is not rendered in the website.

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi  You had rolled back to older version. 
Please rebuild immediately , and send it for a final review .

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi  , what about API docs ?
Can we get them on boarded too if not today atleast on Monday ??
I had done some changes in the API docs too , which have reflected . But the display text needs to be changed & more .html files need to be added to incorporate all APIs

**Comment by kochhar** [comment]
Content is fine. Closing the issue. Tracking changes to the styling: https://github.com/project-sunbird/project-sunbird.github.io/pull/7
