### ISSUE TITLE
API Documentation update 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/sunbird-commons#66]
@manzarul 

These are the APIs provided by you as postman collection . 
1.	User management api 
2.	Organization-Collection 
3.	Metrics APIs 
4.	Email Service 
5.	Course Batch 
6.	Data Sync 
7.	bulk operation 
8.	Page Api 		Schema Missing (definitions)
9.	Health 			Schema Missing (definitions)
10.	Badges 			Schema missing(definitions)

1-7	: I have documented all the API endpoints .
8-10   : Please send the postman collection with definitions (schemas) ASAP .

Also, please send me postman collection for 
1.	Course 
2.	Notes 
3.	Meta 
4.	Telemetry

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi 
I have uploaded these swagger files to yaml folder 
can we get them up and live .

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi Done.

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi thank a lot.

**Comment by nawabahmadreshi** [comment]
This is done and updated .
