### ISSUE TITLE
Sunbird new instance - Application / Functional setup help

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-commons#69]
@vrayulu 

Looking for help in setting up sunbird new instance for end users. For example: 

- Change page title
- Change logo 
- Change fav icon
- Keycloak customisation
- Setting up default org 
- Setting up users
- Loading application data (seed vocabulary, any static data etc) 
- Enable search box 

I am sure there are more than what has been listed. Look forward to your assistance in getting this instance completely functional. Thank you.

@kochhar @madhucr @pramodkvarma @sferoz

**Comment by Sunitashelar** [comment]
@bachia @vrayulu 
information for some of these topics is available
@nawabahmadreshi 
pls check and guide appropriately

**Comment by nawabahmadreshi** [comment]
@vrayulu @kochhar please update these contents in following file:
**Customizing Sunbird **
- Change page title 
- Change logo
- Change fav icon
File Path : 
https://github.com/project-sunbird/sunbird-commons/edit/master/ingredients/developer-docs/customize_sunbird_look_feel.md
- Loading application data (seed vocabulary, any static data etc)
- Enable search box
**Setting Up Sunbird** 
- Setting up  @default org 
https://github.com/project-sunbird/sunbird-commons/blob/master/ingredients/features-documentation/upload_org.md
- Setting up users 
https://github.com/project-sunbird/sunbird-commons/blob/master/ingredients/features-documentation/upload_user.md

**Comment by bachia** [comment]
@Sunitashelar @vrayulu @nawabahmadreshi 

I can see couple of documents on instructions on how to upload Org and Users. I am assuming that these steps must be performed after configuring keycloak. Help on other requirements is much appreciated.

**Comment by vrayulu** [comment]
@coolbung @kochhar - another item that needs documentation is keycloak look and feel customisation. adding it to the above list.

**Comment by bachia** [comment]
@vrayulu How about homepage customization? Shouldn't that be in the list to?

**Comment by vrayulu** [comment]
Yes @bachia... We are working on the following items related to customisation:

1- Customising home page and logo
2- Customising keycloak
3- Themification (fonts, colours, css) of the portal

We will deliver these items in the above order. We are targeting the first item by EOD today and rest by mid next week. Will keep updating this thread.

The second part of application setup is configuring the organisations, users, channels and loading seed data. There is still some work pending on this front. We are planning this out, will publish the timelines for these on Monday.

**Comment by bachia** [comment]
@vrayulu Thank you.

**Comment by bachia** [comment]
@vrayulu Sorry to bother you. Any update on the documentation. Thank you.

**Comment by vrayulu** [comment]
The instructions for setting up custom home page, logo and favicon are documented at https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md#additional-config-to-customize-sunbird-instance. 

Feel free to ping @Manojvv @harishgilimi or me for any issues/queries.

**Comment by bachia** [comment]
@vrayulu 

Just started work on customisations. Can I assume the default tenant name for a fresh instance of Sunbird will be "sunbird" ? I looked into 

`<implementation-name>-devops/ansible/inventories/<environment-name>/group_vars/<environment-name>`

and found this value `sunbird_default_tenant: sunbird`

Thanks for your help.

**Comment by bachia** [comment]
@vrayulu 

> Create the above folder (e.g. /data/extensions/tenant) on all the docker swarm nodes.

Can you help me create this folder on docker swarm node? In our setup we have only one node. Please see below node information. 

![screen shot 2017-10-18 at 7 32 31 am](https://user-images.githubusercontent.com/2817641/31697643-8ba899c8-b3d6-11e7-9cdd-c0d803bda665.png)

**Comment by bachia** [comment]
@vrayulu 

- created /data/extensions/tenant folder structure in our host server 
- created a folder inside "tenant" directory and named it "sunbird" 
- created **index.html** in sunbird folder 
- ran `deploy-proxy.sh` script 

When I try to access our portal I am gettign connection refused. After a minute or two it points back to default home page and not the new index.html.

Any ideas where I am going wrong? Appreciate your help here. Thank you.

**Comment by vrayulu** [comment]
@bachia - just checking: did you have set the variable "player_tenant_dir" value to "/data/extensions/tenant"?

@Manojvv : please provide commands with which we can validate if the volume is mounted and soft link is created properly.

**Comment by bachia** [comment]
@vrayulu, Yes the variable is set with proper value. 

Looks like volume is not mounted properly. See the output of `docker volume ls` command

![screen shot 2017-10-18 at 8 46 58 am](https://user-images.githubusercontent.com/2817641/31699558-34607b62-b3e1-11e7-8f8c-7e050304b35b.png)

**Comment by Manojvv** [comment]
@bachia 
Run `docker service inspect player_player --pretty`  you should see the below fields.
Mounts:
  Target = /home/sunbird/dist/tenant
  Source=/data/extensions/tenant

**Comment by bachia** [comment]
@Manojvv Thank you. I can't find both the fields in the out of the command.

**Comment by Manojvv** [comment]
@bachia 
Listed down steps below, please verify once. 

1)Pull the latest sunbird-devops code. 

2)set the `player_tenant_dir: /data/extensions/tenant`  in `<implementation-name>-devops/ansible/inventories/<environment-name>/group_vars/<environment-name>`.

3)make sure `/data/extensions/tenant` directory is created manually on the instance before running the deploy-core.sh script, with permissions `owner=root,group=root,mode=0775`.

4)Then run `./deploy-core.sh  <implementation-name>-devops/ansible/inventories/<environment-name>`

5)Run the command `docker service inspect player_player --pretty`  to verify the volume mounted or not.

**Comment by bachia** [comment]
@Manojvv Many thanks for detailed instructions. 

I guess I didn't pull the latest code. Now I am getting the following error: 

![screen shot 2017-10-18 at 9 44 40 am](https://user-images.githubusercontent.com/2817641/31700755-1f1c468e-b3e9-11e7-9d6e-af7c9d933b29.png)

**Comment by Manojvv** [comment]
@bachia 
I fixed the above issue and tested. Can you please pull the latest code and follow the above steps.

**Comment by bachia** [comment]
@Manojvv 👍 

It worked. Thanks a bunch for your timely help, mate. 

@vrayulu FYI.

**Comment by bachia** [comment]
@vrayulu awaiting your instructions to proceed further. Appreciate your help.

**Comment by Manojvv** [comment]
@bachia 

We have changed the keycloak setup from docker to vm installation. Keycloak HA setup is not supported in docker as of now. To remove existing keycloak docker service run this command `docker service rm keycloak1`. 

Below steps will help to deploy keycloak on vm. 
`cd sunbird-devops/deploy`

**Keycloak Provision**:
RUN `./provision-keycloak.sh <implementation-name>-devops/ansible/inventories/<environment-name>` this script creates the keycloak username,groupname and servicify keycloak service. 

**Keycloak Deploy:**
Update below variables in the config `<implementation-name>-devops/ansible/inventories/<environment-name>/group_vars/<environment-name>`.
```
1) keycloak_password: (which admin initial password)
2) keycloak_theme_path: ex- path/to/the/nile. sample themes directory of sunbird `https://github.com/project-sunbird/sunbird-devops/tree/master/ansible/artifacts` 
```
Run `sudo ./deploy-keycloak-vm.sh <implementation-name>-devops/ansible/inventories/<environment-name>`.

Note : Updated the document also `https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md` . 

Let me know if you find any issues. Thanks.

**Comment by bachia** [comment]
@Manojvv thank you. 

Managed to execute all the steps listed above without any errors. However,  I am unable to access keycloak admin console. I tried accessing https://dev.ournile.org:8080/auth. Please confirm if the URL is correct. 

I thought it might help you to know the list of ports open on our server. Please find below o/p of netstat command.

![screen shot 2017-10-25 at 3 35 55 am](https://user-images.githubusercontent.com/2817641/31970603-2cdb63e8-b936-11e7-989b-dbbe2f5780d3.png)

**Comment by vrayulu** [comment]
@coolbung  @kochhar - please check the above error and help troubleshoot it.

**Comment by Manojvv** [comment]
@bachia 
Make sure below variables are set in `<implementation-name>-devops/ansible/inventories/<environment-name>/group_vars/<environment-name>` . These are used in both  install-dbs.sh and deploy-keycloak-vm.sh.
 
```
keycloak_postgres_host
keycloak_postgres_database
keycloak_postgres_user
keycloak_postgres_password
```

**Comment by bachia** [comment]
@Manojvv 

I confirm all the variables are set in `<implementation-name>-devops/ansible/inventories/<environment-name>/group_vars/<environment-name>`

**Comment by Manojvv** [comment]
@bachia
Sorry for late reply.
 
Please try below steps 
1.  login to the  db-instance.
2. login to the keycloak postgresql database `<psql -h private_ip_db_instance> -U keycloak -W` , enter the password.
3.  Drop all the tables in the keycloak using the below command, RUN 
```
DROP TABLE admin_event_entity,associated_policy,authentication_execution,authentication_flow,authenticator_config,authenticator_config_entry,broker_link,client,client_attributes,client_default_roles,client_identity_prov_mapping,client_initial_access,client_node_registrations,client_session,client_session_auth_status,client_session_note,client_session_prot_mapper,client_session_role,client_template,client_template_attributes,client_user_session_note,component,component_config,composite_role,credential,credential_attribute,databasechangelog,databasechangeloglock,event_entity,fed_credential_attribute,fed_user_attribute,fed_user_consent,fed_user_consent_prot_mapper,fed_user_consent_role,fed_user_credential,fed_user_group_membership,fed_user_required_action,fed_user_role_mapping,federated_identity,federated_user,group_attribute,group_role_mapping,identity_provider,identity_provider_config,identity_provider_mapper,idp_mapper_config,keycloak_group,keycloak_role,migration_model,offline_client_session,offline_user_session,policy_config,protocol_mapper,protocol_mapper_config,realm,realm_attribute,realm_default_groups,realm_default_roles,realm_enabled_event_types,realm_events_listeners,realm_required_credential,realm_smtp_config,realm_supported_locales,redirect_uris,required_action_config,required_action_provider,resource_policy,resource_scope,resource_server,resource_server_policy,resource_server_resource,resource_server_scope,scope_mapping,scope_policy,template_scope_mapping,user_attribute,user_consent,user_consent_prot_mapper,user_consent_role,user_entity,user_federation_config,user_federation_mapper,user_federation_mapper_config,user_federation_provider,user_group_membership,user_required_action,user_role_mapping,user_session,user_session_note,username_login_failure,web_origins CASCADE; 
```
4. To make sure all the tables  are deleted  in keycloak database, run `\dt`.

5. Delete  manually if any table is not deleted, using `DROP TABLE <table_name> CASCADE;`

6. Try restart of keycloak `sudo /etc/init.d/keycloak start `.

7. You should be able to see the admin dasboard of keycloak `http://keycloak_instance:8080`. Also please make sure port 8080 is open and no other service is running on that port .

**Comment by bachia** [comment]
@Manojvv Thanks again. 

I am getting permission denied error while creating a backup file while server was starting. Please see the relevant log details below. 

>2017-10-25 11:56:26,701 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0082: Failed to create backup copies of configuration file /opt/keycloak/standalone/configuration/standalone-ha.xml
        at org.jboss.as.controller.persistence.ConfigurationFile.successfulBoot(ConfigurationFile.java:484)
        at org.jboss.as.controller.persistence.BackupXmlConfigurationPersister.successfulBoot(BackupXmlConfigurationPersister.java:94)
        at org.jboss.as.controller.AbstractControllerService.finishBoot(AbstractControllerService.java:449)
        at org.jboss.as.server.ServerService.boot(ServerService.java:367)
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.AccessDeniedException: /opt/keycloak/standalone/configuration/standalone_xml_history/standalone-ha.initial.xml
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:243)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at org.jboss.as.controller.persistence.FilePersistenceUtils.copyFile(FilePersistenceUtils.java:73)
        at org.jboss.as.controller.persistence.ConfigurationFile.successfulBoot(ConfigurationFile.java:478)
        ... 5 more

2017-10-25 11:56:26,705 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.

**Comment by bachia** [comment]
@Manojvv 
`standalone_xml_history` folder owner and group seems to be "root". Just changed that to 'keycloak' and restarted the service. It seems to be working...meaning service started and running. 

Still unable to access the admin console though. Let me look through first and come back to you.

**Comment by bachia** [comment]
@Manojvv 

Got it. SSL is not enabled / configured for keycloak. If I enter http://servername:8080 I am getting management console. 

I think we should enable SSL for keycloak also.

**Comment by Manojvv** [comment]
@bachia 

Please set the variable `keycloak_url: http://<privateip_of_keycloak_vm>:8080` and restart the proxy by running `./deploy-proxy <implementation-name>-devops/ansible/inventories/<environment-name>`, it should  fix the above proxy issue.
you can access keycloak admin dasboard at `https://dev.ournile.org/auth/`

For creating keycloak Initial admin user run the below commands
 `cd /opt/keycloak/bin`
`./add-user-keycloak.sh -u <keycloak_admin_username> -p <keycloak_admin_password>`

**Comment by bachia** [comment]
@Manojvv 

Thank you confirmed working.

**Comment by nawabahmadreshi** [comment]
https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md#additional-config-to-customize-sunbird-instance.

@vrayulu @Manojvv  

Is this file for customization complete or are there any changes ? 
cc:
@Sunitashelar

**Comment by kochhar** [comment]
@bachia I'm closing this issue since it seems to be resolved for now. Please feel free to re-open or to add for new problems encountered.
