### ISSUE TITLE
 Contribution Section for Sunbird Website 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/sunbird-commons#72]
Hello Team, 
We need to put up the contribution section for sunbird website . 
Put comments and suggestions if any. 
cc:
@Sunitashelar 
@kochhar 
@deepshikha2k5 
@Basreena 
@vrayulu

**Comment by nawabahmadreshi** [comment]
@kochhar , kindly suggest the point of contact for contribution section .
Also once you had said that we have some wiki or some doc related to it , can you provide the link .

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/project-sunbird.github.io #25](https://github.com/project-sunbird/project-sunbird.github.io/issues/25) via [**ZenHub**](https://www.zenhub.com/)
