### ISSUE TITLE
Sidebar Tweaks

### ISSUE THREAD

**Issue by lakhanmandloi** [project-sunbird/sunbird-commons#74]
@nawabahmadreshi  -  Hi,
As mentioned in https://github.com/project-sunbird/project-sunbird.github.io/pull/7 can you pls send me the changes that needs to be done on site?  I am available today. And might not be available tomorrow onwards (Planned to work on societal site), So can you pls send me the list asap today itself. 

Thanks!

cc:
@parthlawate

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi 
1. Sidebar needs to be collapsible / dynamic in nature . 
2. How can we change picture sizes in markdown or in the linking braces { ....}
Kindly,can you send the correct format as to how we can do it .

cc:
@Sunitashelar 
@Basreena 
@deepshikha2k5

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi 

- For Image sizing pls go with this - https://github.com/BranchMetrics/documentation#image
- For Dynamic and Collapsible Sidebar , i had already mentioned in https://github.com/project-sunbird/sunbird-commons/issues/73 .

**Comment by deepshikha2k5** [comment]
@lakhanmandloi 
Kindly, let me know if we make changes in the .md files does it reflect automatically in the website.

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi , is site rebuild automated now ?

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi not completely.

**Comment by lakhanmandloi** [comment]
I mean it is ready. But after review of process there were some feedbacks from Shailesh, So i have to fix those first or migrate site to new theme. For the same reasons the issue is opened - https://github.com/project-sunbird/sunbird-commons/issues/73

**Comment by deepshikha2k5** [comment]
@lakhanmandloi 
We wanted to re-build the site, since we are reviewing each piece of content from our end and at few places the changes are entertained. Once all the changes are made, we will notify you to give build by today.

**Comment by lakhanmandloi** [comment]
@deepshikha2k5 ok.
