### ISSUE TITLE
Information needed on "Sunbird Services Setup"

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/sunbird-commons#76]
@steotia @endeepak @Manojvv 
We need information on Sunbird Services Setup

You can check this 

http://www.sunbird.org/developer-docs/
TRY SB https://staging.open-sunbird.org/#!/
EXTEND SB http://www.sunbird.org/developer-docs/developer_install/
MED SC DEPLOY http://www.sunbird.org/developer-docs/medium_scale_deploy/
LARGE SC DEPLOY https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md
Kindly clarify  
**The below link refers to ?**
https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md
**Large scale deployment or what  ??**
cc:
@Sunitashelar

**Comment by endeepak** [comment]
@nawabahmadreshi Currently https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md refers to medium scale deployment. This will be enhanced for more complex scenarios which can be used by large scale deployment

Are you planning to copy the content from above file or just provide a link to above file on documentation site?

**Comment by kochhar** [comment]
The docs will all live on the sunbird docs site, it's fine to stage them in
wikis.

We need to document the installation of services for a developer
installation. Presently we have details on how to run the portal for a
developer and how to run services for mid-size cloud install.

We also need to have details on how to run the services as a developer and
how to run the portal in a mid-size cloud install.

**Comment by nawabahmadreshi** [comment]
@endeepak  thanks a lot for this information , I just had a doubt about where this doc fits in. 
@kochhar , I will copy the above content and place it in appropriate location so that it becomes available on our website .
