### ISSUE TITLE
Developer Install docs code blocks are broken

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/sunbird-commons#95]
@nawabahmadreshi Please see this page: http://www.sunbird.org/developer-docs/developer_install/

Bottom part of the page:
Edit the application config:

The code block formatting is broken. The code should be formatted as a block and not as inline code. When formatting it as a block one config entry should appear on every line.
http://www.sunbird.org/developer-docs/developer_install/

**Comment by nawabahmadreshi** [comment]
@kochhar, agreed and will do the necessary changes.

**Comment by kochhar** [comment]
@nawabahmadreshi could you estimate when will this be completed? Formatting is still broken on the website for multiple sections.

cc: @Sunitashelar

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/project-sunbird.github.io #21](https://github.com/project-sunbird/project-sunbird.github.io/issues/21) via [**ZenHub**](https://www.zenhub.com/)
